### ISSUE TITLE
The GPL3 license

### ISSUE THREAD

**Issue by blurymind** [ct-js/ct-js-old#102]
First of all thank you for open sourcing this wonderful js game engine. I am one of the contributors on gdevelop and have been following your work quietly over the last few months.

Your engine definitely has some wonderful design choices in it.

Now I just want to say that I love gpl3 and open source licenses in general, however I am painfuly aware that game engines have a troubled past with the license you have chosen for yours.
The problem is the viral nature of the license. If you develop a game with an engine with it, you have to release your game's source code- at which point you kind of kill any serious adoption from developers who are in it to make a living.

This is the reason many successful open source engines use the MIT license instead.They still license the name of their engine, but the actual code is mit. See godot, gdevelop, phaser, etc etc. Some of these engines get successfully funded by studios that use them. If you are interested in getting that sort of funding, you will need to consider the adoption of the engine when it has that license.

Either way, I would be curious to hear the reason for going with gpl3 over mit or bsd or any of the non-viral ones.
This is one of the unfortunate things that has kept open source game engines from being adopted by industry for years- the viral nature of the license. It is imo one of the main reasons the blender game engine died after having very poor adoption. Nobody actually made commercial games with it as a result :(

**Comment by CosmoMyzrailGorynych** [comment]
Sometimes I regret not being a lawyer 😅 

@blurymind That was indeed a silly move to make ct.js GPL-3 licensed when all the exported projects contain ct.js code — that was not intended at all. My aim is to make ct.js available for everyone, and applicable for commercial use, and I think it will be better for everyone if ct.js is released under a simpler license (MIT).

Thank you for pointing all this out! I'll leave the issue opened while I replace the license.
