### ISSUE TITLE
More obvious highlighting of paired braces

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#104]
**Describe the current state of the problem**
Right now, a paired bracket is outlined with a gray square, which is poorly visible and works at specific cursor positions.

![image](https://user-images.githubusercontent.com/3174357/63207318-c8df5980-c117-11e9-8bad-470bae591cea.png)

![image](https://user-images.githubusercontent.com/3174357/63207322-df85b080-c117-11e9-9fe9-e603ccbc894b.png)

**Describe the solution you'd like**
When you put a cursor in the code next to the curly bracket, then this curly bracket and its pair should be highlighted in a more noticeable color.

As seen in VSCode: 
![image](https://user-images.githubusercontent.com/3174357/63207327-f88e6180-c117-11e9-8770-b01b87075a30.png)

**Describe alternatives you've considered (optional)**
A color highlight for all the brackets (aka rainbow brackets in most code editors).

As seen in VSCode & Horizon theme (too messy, I guess?): 
![image](https://user-images.githubusercontent.com/3174357/63207334-207dc500-c118-11e9-9d86-54acf45e4e89.png)

**Comment by qualitymanifest** [comment]
![ctjs](https://user-images.githubusercontent.com/13897419/63230053-b0357900-c1d5-11e9-81ce-a3e0f449bf62.gif)

How's that? I tried to copy the behavior from vscode where, in case there is brackets on both sides of the cursor, it will highlight the one to the right. If there is only one bracket touching the cursor it will highlight it regardless of which side it's on.

The Ace editor doesn't provide a configuration option for this (they have a couple [open](https://github.com/ajaxorg/ace/issues/2424) [issues](https://github.com/ajaxorg/ace/issues/3949) about it) so I had to modify the `$highlightBrackets` function in `ace.js`. Is that OK or is there somewhere better where I can override that editor function?

**Comment by CosmoMyzrailGorynych** [comment]
In my opinion, the best way (in the long term) is to create a fork and implement these changes in it, then use the fork as a submodule. I'll set up compiling and linking for that if you create such a fork.

A short-term solution is to directly edit [ace.js](https://github.com/ct-js/ct-js/blob/develop/src/js/3rdparty/ace/ace.js) at ct.js, but one upstream update comes — and the changes are swallowed up.
