### ISSUE TITLE
Distribute ct.js in a Flatpak

### ISSUE THREAD

**Issue by LeandroStanger** [ct-js/ct-js-old#107]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by CosmoMyzrailGorynych** [comment]
Flathub will be a good distribution channel for a vast Linux userbase. And I'm positive in general towards flatpak as a package manager.

I haven't build flatpak apps before, so if someone knows how to distribute such apps, you can make it faster than me, maybe even before the v1.0.0-next-4 launches. Then we can merge it in the official pipeline with a proper ci/cd integration. *(I love CI :smile: )*

**Comment by CosmoMyzrailGorynych** [comment]
[Setting file system permissions for Flatpak apps](https://github.com/Taiko2k/TauonMusicBox/wiki/Flatpak-Permissions)

**Comment by firecakes** [comment]
Hi 👋 I'm interested in figuring out how to make a ctjs flatpak. I now have the necessary environment to try building one.

**Comment by leedigital** [comment]
> Hello wave I am interested in figuring out how to make a ctjs flatpak. I now have the necessary environment to try to build one.

This is also on my to-do list, but my time is short and I'm doing what has higher priority.... But if you are willing to try to build this package.... Count on me if you need any help.
