### ISSUE TITLE
background image movement speed

### ISSUE THREAD

**Issue by lumosmind** [ct-js/ct-js-old#109]
v1.0.0-next-3
win 10-64bit

I just download for try your project and I figured out a bug. 
create new project with minimal default settings.
add texture image for background.
create new room.
add background image to the room.
in background settings menu with default settings plus
repeat: no-repear
movement 
  x: 0
  y: 10
click save and run. => nothing moves
with
repeat: no-repear
movement 
  x: 10
  y: 0
click save and run. => background image moves vertically but I expected that it will move horizontally.

**Comment by CosmoMyzrailGorynych** [comment]
Thanks for the report! The issue got fixed 👌
