### ISSUE TITLE
There's no ct.mouse.clear() function

### ISSUE THREAD

**Issue by edumaxsantos** [ct-js/ct-js-old#112]
**Describe the bug**
The console shows an error saying there's no ct.mouse.clear() function when you click on Start.

**To Reproduce**
Just followed https://docs.ctjs.rocks/tut-making-shooter.html#adding-player-s-movement and it already stops working when trying to Start the game.

**Expected behavior**
The game should just work, but it keeps on an empty screen with an error message on the console.

**Versions:**
 - OS: Windows 10
 - ct.js version 1.0.0-next-3

**Comment by CosmoMyzrailGorynych** [comment]
I'll roll out a fix shortly; for now, you can continue the tutorial by disabling `mouse.legacy` and enabling the regular `mouse` in your catmods. The problem lies in the fact that ct re-applies the conversion again once you re-open the project.
