### ISSUE TITLE
Packaging games for macOS: same issues that existed for ct.js itself

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#115]
**Describe the bug**
As ct.js uses the same nw-builder for packing its games, they inherit all the problems that a vanilla nw-builder has:

- setting a Win icon fails on Linux;
- macOS packages don't open for a couple of reasons:
  - wrong rights on executables (no `+x` flag);
  - absolute symlinks instead of relative ones, that work only for one computer :woman_facepalming:
- building for macOS on Windows is thus not possible, because:
  - Windows do not have a `+x` flag;
  - Windows do not support symlinks, only junctions.

**To Reproduce**
1. Pack a game for macOS
2. Get a non-working package (:

**Expected behavior**
Ct.js should pack games for macOS on any system

**Versions:**
 - OS: any
 - ct.js version: 1.0.0

**Comment by CosmoMyzrailGorynych** [comment]
A possible solution is to use electron instead of nw.js all over the project. This won't change anything for users, and migration will be quite smooth, I suppose, as they have a similar API for menus and shell.

Research is still needed: maybe electron cannot be packed for Mac from Windows as well because symlinks are in the chromium binaries on which both frameworks rely on.

**Comment by erlend-sh** [comment]
I would recommend having a look at https://github.com/tauri-apps/tauri

It's still a bit early, but we're gonna be using it for [Amethyst](https://github.com/amethyst/amethyst) in our own editor project [atelier-editor](https://github.com/amethyst/atelier-editor).

**Comment by CosmoMyzrailGorynych** [comment]
Closed in favor of #174
