### ISSUE TITLE
ct.place.occupied and ct.place.free could also accept type names as its argument for phantom checks

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#117]
**Describe the current state of the problem**
Currently, `ct.place.occupied` and `ct.place.free` accept only copies (and copy-like objects) as its first argument (`ct.place.free(copy: Object, [x, y, cgroup])`). That works well in most situations, but, in cases when we need to check a possible collision before _creating_ a new copy, we should either create a copy first or use a fake copy-like object to test against. First (most obvious) solution can lead to unwanted results, as there can be a lot of location-dependent code in a copy's OnCreate event.

**Describe the solution you'd like**
`ct.place.occupied` and `ct.place.free` could use a notation of `ct.place.free(typeName: String, x, y, [cgroup])`. This will allow safe checks of collisions before creating any copy.

**Describe alternatives you've considered (optional)**
We can use fake copy-like objects to check for collisions. E.g. a test against a centered 32x32 rectangle:

```js
ct.place.free({
  scale: {
    x: 1,
    y: 1
  },
  rotation: 0,
  shape: {
    type: 'rect',
    left: 16,
    right: 16,
    top: 16,
    bottom: 16
  }
}, x, y, ctype);
```

**Additional context**
There's a problem with a proposed solution: it cannot take transformation info.

**Comment by Sweetkubuni** [comment]
I can help with this issue

**Comment by CosmoMyzrailGorynych** [comment]
@Sweetkubuni Cool! Keep us up to date with its solution 😄

**Comment by CosmoMyzrailGorynych** [comment]
A better alternative is adding a special module for this task, like `ct.place.projectType(typeName, x, y, ctype, transforms)`, where `transforms` is optional and is an object with `rotation` and `scale.x`, `scale.y` properties. Returns `true` if meets a collision

**Comment by amsam0** [comment]
I'd like to make an attempt on this.
