### ISSUE TITLE
Demos: add support for touch controls

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#121]
**Describe the current state of the problem**
Currently, only the ["Memocats"](https://comigo.itch.io/memocats) demo supports running on phones as it does not require keyboard controls. "Catsteroids" and "Catformer" (aka Greed) require them and thus are unplayable on touch devices like phones. As these are the demos of ct.js, they should reflect state-of-the-art features of ct.js, and thus need to be upgraded.

Ct.js now does have easy tools for creating touch-aware games, by its `ct.touch` and `ct.vkeys` modules.

**Describe the solution you'd like**
["Catsteroids"](https://comigo.itch.io/catsteroids) and ["Greed"](https://comigo.itch.io/catformer) should support playing on phones and other touch devices, preferably by adding joysticks (for "Catsteroids") and virtual keys (for both).

**Comment by amsam0** [comment]
Could we use the 'vkeys' catmod to do this? I was able to add buttons to the platformer tutorial very quickly, but I haven't tested it on mobile.

**Comment by amsam0** [comment]
I'm happy to work on this if you dont mind.
