### ISSUE TITLE
Colliders do not collide properly

### ISSUE THREAD

**Issue by MMLich** [ct-js/ct-js-old#124]
**Describe the bug**
Some of my objects do not collide as they should, sometimes even collide outside each other's shape. It slightly seems like the colliders of objects are somehow shifted from their position.

**Expected behavior**
I set up colliders for space trash and laser beam in the space shooter game. But they are not computed properly. Objects are slowly rotating and are randomly resized at the beginning of the game. Each piece of space trash had the rectangle shape and the laser have the same shape as well.
The laser beam should end at the moment it hit the space trash. But the beam sometimes goes through the objects. And my rocket sometimes collides with the trash even if it is outside its shape (rocket has polygon shape).

**Screenshots (recommended)**
The glitch:
![obrazek](https://user-images.githubusercontent.com/55833136/65717133-ea314f00-e0a0-11e9-8689-c35be2278cb7.png)

The colliders:
![obrazek](https://user-images.githubusercontent.com/55833136/65717188-07feb400-e0a1-11e9-83bc-c95e58039080.png)

**The code:**
Space trash object (OnCreate):
```
    this.undestroyable = true;

    this.rotation = (ct.random(360));
    this.scale.x = (ct.random(3) + 0.5);
    this.scale.y = this.scale.x;
    this.rotationSpeed = ct.random(0.5);
    this.x += (ct.random(500) - 250);
    this.y += (ct.random(500) - 250);
```

Space trash object (OnStep):
`    this.rotation += this.rotationSpeed * ct.delta; //trash is not moving`

Function called on player:
```
    function createLaser(player, dir) {
        var direction = (player.direction + dir) % 360;
        if (ct.room.timer < 300) return;
        i = 0;
        while (true) {
            i++;
            var laser = (ct.types.copy("Laser", player.x + ct.u.ldx(25 * i, direction), player.y + ct.u.ldy(25 * i, direction)));
            if (laser.x < 0 || laser.x > ct.roomWidth || laser.y < 0 || laser.y > ct.roomHeight) {
                return;
            }
            laser.rotation = (direction + 90) % 360;
            for (var collider of ct.place.occupied(laser, laser.x, laser.y, 'Hitable', true)) {
                if (collider != player) {    //ship cannot shoot itself
                    laser.show();             //collision effect
                    if (!collider.undestroyable) collider.kill = true;
                    if (collider.hp)
                        collider.hp -= ct.delta;
                    return;
                }
            }
        }
    }
```

**Versions:**
 - OS: Windows 10
 - ct.js version: 1.0.2

**Comment by CosmoMyzrailGorynych** [comment]
What a marvelous, detailed bug report! :3

> my rocket sometimes collides with the trash even if it is outside its shape 

@MMLich, does it make falsey collisions on a relatively big distance, or only when they are separated by 2-3 pixels? The collision engine treats transformed shapes and polygons as 3-pixels wide line segments.

**Comment by MMLich** [comment]
@CosmoMyzrailGorynych, the distance quite greater than a few pixels. My rocket is very small. But I think that it sometimes collides with about 30 pixels distance from obstacles. Sorry for no pictures, but I am not at home at the moment. I can add pictures tomorrow.

**Comment by MMLich** [comment]
![obrazek](https://user-images.githubusercontent.com/55833136/65819109-05bf6580-e219-11e9-8fbb-0f9977a78e59.png)
The ship object drops the blue laser as it moves so the collision spot is visible at the picture. I've disabled the rotation of space trash (I rotated it only at start). So this is exactly the point where they collide (and the area where they didn't collide).

**Comment by CosmoMyzrailGorynych** [comment]
So I've found at least one bug that causes this behavior: unclosed shapes

![изображение](https://user-images.githubusercontent.com/3174357/65849233-93c45900-e39d-11e9-9cab-e0f6782a4ab3.png)

**Comment by CosmoMyzrailGorynych** [comment]
Holy cow.

![изображение](https://user-images.githubusercontent.com/3174357/65850121-9c1e9300-e3a1-11e9-92f7-1f390269d49d.png)

**Comment by CosmoMyzrailGorynych** [comment]
The fix will be shipped in the nearest release
