### ISSUE TITLE
Ability to change Sprites hue

### ISSUE THREAD

**Issue by MMLich** [ct-js/ct-js-old#130]
**Is your feature request related to a problem?**
If I want to create for example randomly generated characters with different colors of hair, skin, clothes, etc. I must use different textures. 

**Describe the solution you'd like**
The ability to change the hue of sprites would be very helpful. 
This would allow a programmer to create a variety of objects with the same texture and save time and hard drives.
In-script changing would be the best for creating fancy effects and generating.

**Comment by CosmoMyzrailGorynych** [comment]
I thought you were talking about changing textures inside ct.IDE, like in YoYo Game Maker with its hue rotation :upside_down_face: 

In ct.js, the general approach for that is creating a mostly white texture with shadows (a texture of white hair, white dress, etc.) and then colorize it in the game with `this.tint = 0xff0000;`
The thing after `0x` is a HEX color. This is applicable for most pixi objects, not just ct.js Copies.

**Comment by MMLich** [comment]
Oh, I didn't know that. Yes, I mean hue rotation, but the tint is a better way. I am not familiar with Pixi much. Though, changing textures inside IDE would be cool as well.

**Comment by MMLich** [comment]
Oh, I didn't know that. Yes, I mean hue rotation, but the tint is a better way. I am not familiar with Pixi much.
 Though, changing textures inside IDE could be cool as well.

Overall: sorry for bothering and thanks for your help.
