### ISSUE TITLE
ct.flow, ct.u.wait, ct.tween should operate based on ct.delta, with optional setTimeout mode

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#151]
**Describe the current state of the problem**
`ct.flow`, `ct.tween` and the built-in method `ct.u.wait` all work with time. Internally, they use `setTimeout`, which is good for UI and most gameplay-related cases, but will fail if a game developer uses slo-mo effects or has, in the opposite, time acceleration controls (a la Sims), as these change ct.delta on which is based all the ct.js' logic.

**Describe the solution you'd like**

All time-based methods should work with ct.delta by default. Optional parameters should be present to enable the old behavior, as it is needed for UI and other events that are off the main game loop. I think it is safe to name all these cases as UI actions.

For example:

* `ct.tween.add` gets a new parameter in its options, `ignoreDelta`;
* `ct.flow.timer` and others get an optional argument `ignoreDelta`.

**Comment by amsam0** [comment]
Could I work on this?

**Comment by CosmoMyzrailGorynych** [comment]
@naturecodevoid, sure! I now think, though, that there should be pairs of methods instead of methods with additional options (`ct.tween.add` and `ct.tween.addUi`, for example), as it will be more readable and and uniform compared to existing methods in ct.mouse and ct.touch.

**Comment by amsam0** [comment]
I've been trying to use `setInterval` for a timer using `ct.delta`/`ct.deltaUi`, but I'm having some trouble getting it to work. Should I make a commit to my fork? Or I could paste a code snippet here.

**Comment by CosmoMyzrailGorynych** [comment]
Both are fine 👍

I think that ct.tween and others should be reworked to work more like vanilla timers that update at each frame (there are "injections" that allow to place code at specific positions, see https://docs.ctjs.rocks/making-mods.html). But if setInterval will work, it will be fine too.

**Comment by amsam0** [comment]
Here's the code: 
```javascript
 /**
     * Returns a Promise that resolves after the given time
     * @param {number} time Time to wait, in milliseconds
     * @param {object} [options={}] An object with options
     * @param {boolean} [options.useUiDelta=false] If true, use ct.deltaUi instead of ct.delta 
     * @param {boolean} [options.useTimeout=false] If true, use setTimeout() instead of ct.delta
     * @returns {Promise<void>} The promise with no data
     */
    wait(time, options = {}) {
        var room = ct.room.name;
        var options = {
            useUiDelta: options.useUiDelta || false,
            useTimeout: options.useTimeout || false
        };
        if ((options.useUiDelta && options.useTimeout) == true) {
            return new Promise((resolve, reject) => {
                reject({
                    info: 'Both options are true',
                    from: 'ct.u.wait'
                });
            });
        }
        if (options.useTimeout) return new Promise((resolve, reject) => setTimeout(() => {
            if (ct.room.name === room) {
                resolve();
            } else {
                reject({
                    info: 'Room switch',
                    from: 'ct.u.wait'
                });
            }
        }, time));
        return new Promise(function (resolve, reject) {
            let time_a = 0; // Timer time
            let timer; // Timer
            const intervalClear = function () {
                clearInterval(timer);
            }; // Function to clear the setInterval, not sure if needed
            timer = setInterval(function () {
                if (ct.room.name === room) {
                    time_a += options.useUiDelta ? ct.deltaUi : ct.delta; // Add time
                    if (time_a * 1000 >= time) {
                        resolve() && intervalClear(); // If the timer is done, resolve and clear the interval
                    }
                } else {
                    reject({
                        info: 'Room switch',
                        from: 'ct.u.wait'
                    }); // Reject if the room was switched
                }
            }, 1);
        });
        /*return new Promise((resolve, reject) => setTimeout(() => {
            if (ct.room.name === room) {
                resolve();
            } else {
                reject({
                    info: 'Room switch',
                    from: 'ct.u.wait'
                });
            }
        }, time));*/
    }
```
It's pretty messy and I still need to seperate the different modes. I'll look at the injections thing, looks promising (Or I'll just edit the code directly). Maybe `ct.timers`? It could be expanded to hold more than the internal timers. Maybe a feature that automatically add delta to a timer, so a game dev doesnt have to manage it themselves.

Edit: Maybe a for loop that only adds `ct.delta` if it's different from the last one? Probably the injection/`ct.timers` would work better.

**Comment by amsam0** [comment]
I'm going to try the injections/editing the loop code thing.

Edit: Would you mind if I try to create `ct.timer`?

Edit 2: ~~What is the process for making a new module?~~ Pretty sure I mostly figured it out.

Edit 3: Tried it here: https://github.com/ct-js/ct-js/pull/179 ~~but `timer.js` isn't added to the export~~

**Comment by CosmoMyzrailGorynych** [comment]
> Edit: Would you mind if I try to create ct.timer?

@naturecodevoid better expand ct.js' core library, as timers are pretty essential to gamemaking
