### ISSUE TITLE
Monaco editor marks functions defined in scripts as unknown

### ISSUE THREAD

**Issue by Wend1go** [ct-js/ct-js-old#154]
**Describe the bug**
Functions that are written in a script are marked with a red squiggly line in the new Monaco based editor.

**To Reproduce**
1. Add a new project
2. Add a new script in the settings tab and create a function
3. Add a new room and create a room event
4. Call the function that was defined in the script
5. The editor marks it in red and shows "Cannot find name 'MyFunction'"

**Expected behavior**
The editor should not show red squiggly lines under defined functions.

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/7413059/69611897-087ae300-102f-11ea-920b-dd6109639c08.png)

**Versions:**
 - OS: any
 - ct.js version: 1.2.0

**Comment by CosmoMyzrailGorynych** [comment]
Yes, currently the editor is clueless about what happens outside itself and outside type definitions of ct or catmods ¯\_(ツ)_/¯
