### ISSUE TITLE
Ct.js exporter as a stand-alone node module

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#163]
**Is your feature request related to a problem?**
Not quite, but it will open avenues to a couple of things:

* CI/CD for games, with live previews for merge requests and automatic deployment without any PC (a dream!);
* using ct.js as a framework separately from ct.IDE, whilst keeping a common project format.

**Describe the solution you'd like**

The exporter could be a stand-alone module, without the requirement for a browser. Browsers will speed up drawing atlases, while bare node environments can use Cairo canvas.

**Describe alternatives you've considered (optional)**

* Using ct.IDE as a CLI tool for building, which is cool as well.

**Comment by yonderbread** [comment]
Love this plan, also I wasnt aware the ctjs executable had CLI capabilities?
