### ISSUE TITLE
Error exporting project

### ISSUE THREAD

**Issue by grishy** [ct-js/ct-js-old#165]
**To Reproduce**
1. Open Memocats
2. Export the Project
3. Export

Using v0.34.1 (normal)
Error: EROFS: read-only file system, mkdir '/private/var/folders/2s/p2z2fbrj7rl_74d9tt9z2l_r0000gn/T/AppTranslocation/F4E00742-2E0A-41DE-AA72-6A244E86A13D/d/ctjs.app/Contents/Resources/app.nw/cache/0.34.1-normal/osx64'

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/13949080/71541697-05487f00-296e-11ea-8822-865da73d7952.png)

**Versions:**
 - OS: macOS 10.15.2 (19C57)
 - ct.js version 1.2.1

**Comment by CosmoMyzrailGorynych** [comment]
Also see #115

**Comment by CosmoMyzrailGorynych** [comment]
Closed in favor of #174
