### ISSUE TITLE
Error on adding particle effect

### ISSUE THREAD

**Issue by Wend1go** [ct-js/ct-js-old#171]
**Describe the bug**
When hitting the "Add" button in the FX tab the error in the screenshot is displayed in the console.
The particle editor doesn't show up.

**To Reproduce**
1. Create a new project
2. Click on the "FX" tab
3. Hit the "Add" button

**Expected behavior**
The particle editor should show up

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/7413059/75250927-cd2cb380-57d9-11ea-9089-fdbab20121c3.png)

**Versions:**
 - OS: Windows 10
 - ct.js version: git from 25.02.2020 (self built)

The IDE was built according to the description:
https://github.com/ct-js/ct-js#forking-and-installing-the-dev-environment

**Comment by CosmoMyzrailGorynych** [comment]
Nice catch! Fixed :ok_hand:
