### ISSUE TITLE
backgroud image show weird gaps

### ISSUE THREAD

**Issue by uemganix** [ct-js/ct-js-old#175]
**Describe the bug**
any project created by myself showing weird gaps on the background image, however official example projects run good with no gaps

**To Reproduce**
create a new project 
create a room and add a background image with repeat on both x and y axis
run the project

**Screenshots (recommended)**
![capt](https://user-images.githubusercontent.com/20217288/76165036-a2a20980-618e-11ea-9321-10d7abb1ab8c.PNG)

**Example project (strongly recommended)**
[test.zip](https://github.com/ct-js/ct-js/files/4303348/test.zip)

**Versions:**
 - OS: Windows 10
 - ct.js version 1.2.1

**Comment by CosmoMyzrailGorynych** [comment]
You should mark the background as such in its settings. See https://docs.ctjs.rocks/troubleshooting-teared-background.html

**Comment by CosmoMyzrailGorynych** [comment]
Btw you've sent me an empty project. Don't forget to save your projects first :wink:
