### ISSUE TITLE
Seed Randomizer 

### ISSUE THREAD

**Issue by spaced-out-factory** [ct-js/ct-js-old#187]
This is more of a feature request than an issue. Wouldn't it be cool if we could use a seed Randomizer so we could make procedural games like no man's sky and Minecraft except it would be 2d instead of 3D. What does everybody think about this idea?

**Comment by CosmoMyzrailGorynych** [comment]
It is without doubt a nice feature to have built-in 👍

**Comment by amsam0** [comment]
Maybe a catmod?

**Comment by CosmoMyzrailGorynych** [comment]
I think that ct.random is the most  logical place to add this feature

**Comment by CosmoMyzrailGorynych** [comment]
btw @zachdyer if you want this functionality right now, you can write it in 5 lines of code or so; Google has lots of examples
