### ISSUE TITLE
ct.rooms.merge prefab multiple times breaks ct.place.tile

### ISSUE THREAD

**Issue by wesleywerner** [ct-js/ct-js-old#191]
**Describe the bug**
Calling `ct.rooms.merge` to load parts of a room from prefabs works only if you load the prefab once. When loading the same prefab a second (or more) times into the same room, then the tileLayer.tiles instance for subsequent calls points to the first instance -- thus updating the tiles array positions clobbers the first insance's tiles, breaking any future calls to `ct.place.tile`.

For tile-based games where there a lots of tiles, you don't want to create a Type for each tile that can block the player. Thus drawing all blocking tiles to a layer with a depth of `-5` and calling `ct.place.tile` to test for collisions is the most optimal solution.

**To Reproduce**
1. Create a Prefab room
2. Add a tile layer with depth `-5`, set a tileset image and draw some blocking tiles.
3. Create a Main room and in the On Create Room Event load the prefab with `ct.rooms.merge`, applying offsets to the tileLayer (for drawing position) and for its `tiles` array (for collision detection)
4. Repeat step `3` with different offsets, to give two copies of the same prefab in your room
5. Any calls to `ct.place.tile` fails when over the tiles placed in point `3`. 

**Expected behavior**
Each subsequent call to `ct.rooms.merge` should give the copy of `tileLayer` its own `tiles` object array, allowing you to merge the same prefab more than once in the current room.

**Screenshots**

Test control: First and Second blocks merged from TWO different prefabs:

_First control: blocks player_  

![2020-05-17 08_41_27-ct js game — ct js](https://user-images.githubusercontent.com/551913/82131977-48709500-981e-11ea-9037-aab064d0b033.jpg)

_Second control: blocks player_

![2020-05-17 08_41_57-ct js game — ct js](https://user-images.githubusercontent.com/551913/82131987-50303980-981e-11ea-826d-6c4bb9ad7415.jpg)

Test: Merging the Second prefab in again (as Third):

_Test: Second does not block the player any more_

![2020-05-17 08_43_05-ct js game — ct js](https://user-images.githubusercontent.com/551913/82131989-58887480-981e-11ea-96d5-92a7d14bf0e6.jpg)

_Test: Third does block_

![2020-05-17 08_43_16-ct js game — ct js](https://user-images.githubusercontent.com/551913/82131990-5f16ec00-981e-11ea-8ef9-1739be7bee24.jpg)

**Example project**
[roommergebugsample.zip](https://github.com/ct-js/ct-js/files/4639398/roommergebugsample.zip)

- Open Room "Main Level" and enter Room Events.

**Versions:**
 - OS: Windows 10 x64
 - ct.js version 1.3.1

**Thanks**

I want to say thanks to everyone involved in this project, it is a lovely tool :)

**Comment by fgoo** [comment]
Hi,

May be related to this issue in append.

I have 3 scenes, calling from main scene Map1 and Map2 as bellow:
```
ct.rooms.append('Map1', {
    isUi: true
});
ct.rooms.append('Map2', {
    isUi: true,
    y: 2500
});
```
Map1 Types OnStep Scripts works great.
Map2 Types OnStep Scripts don't work.


Regards,

**Comment by CosmoMyzrailGorynych** [comment]
`ct.rooms.append` and `ct.rooms.merge` are different at their mechanism, yet ct.place should work with all the tile layers. This will mostly surely require an API change. Probably it will be `ct.place.tile(copy, x, y, cgroup)`, where cgroup is a string, a collision group used in types.

**Comment by CosmoMyzrailGorynych** [comment]
To prevent breaking code, ct.place can look at tileLayer.depth if it does not have tileLayer.cgroup.

This issue is also a good opportunity to add moddable fields to tile layers

**Comment by CosmoMyzrailGorynych** [comment]
Well, the issue is in another place: it is in object linking at tiles that causes such snippets:

```js
copy.tiles.forEach((t) => {
        t.x += 64;
        t.y += 64;
    });
```

To be called numerous times on the same four objects. (Call your prefab code and notice how prefabs spawn at different position on each call.)

Tho I still implemented collision groups for tile layers XD

**Comment by CosmoMyzrailGorynych** [comment]
Ayyyyyy

![Peek 2020-06-23 12-58](https://user-images.githubusercontent.com/3174357/85349015-6635c600-b551-11ea-8c65-ad2a438ce2dc.gif)

**Comment by CosmoMyzrailGorynych** [comment]
I also currently recommend shifting visual tiles instead of moving their tileset until #128 is settled:

```js
// Insert single prefab twice -- works
var data = ct.rooms.merge('Single Prefab');
for (const copy of data.tileLayers) {
    // offset the layer -- for drawing position
    copy.children.forEach((t) => {
        t.x += 64;
        t.y += 128;
    });
    // offset the tiles -- for collisions
    copy.tiles.forEach((t) => {
        t.x += 64;
        t.y += 128;
    });
}
```

**Comment by wesleywerner** [comment]
Excellent, thanks for all your effort on this wonderful project, Cosmo!
