### ISSUE TITLE
JettyCat example broken

### ISSUE THREAD

**Issue by SilverSight1** [ct-js/ct-js-old#198]
# TODO

- [x] Fix ct.tween
- [x] Update the tutorial

---

Hi. I've been following the tutorial included inside of ct.js, and in the polishing JettyCat section, we make the rooms UI_Paused, and UI_OhNo fade in from 0 alpha. UI_OhNo works as intended, but UI_Paused doesn't show any UI (the continue button still works though).

**To Reproduce**

add
---

this.alpha = 0;

ct.tween.add({
    obj:this,
    fields:{
        alpha:1
    },
    duration:500
});

---
under the On Create for room UI_Paused.

**Expected behavior**
Room UI_Paused should fade in exactly the same way UI_OhNo does.

**Versions:**
 - OS: Manjaro Linux 20.0.2
 - ct.js version 1.3.1

**Comment by CosmoMyzrailGorynych** [comment]
Honestly, the issue sounds invalid; could you send your project so I can reproduce it 100% and find the problem?

**Comment by SilverSight1** [comment]
[cattyJetpractice.zip](https://github.com/ct-js/ct-js/files/4790292/cattyJetpractice.zip)

**Comment by SilverSight1** [comment]
I'm having the same problem with the finished example provided under ctjs > examples > JettyCat.ict

**Comment by CosmoMyzrailGorynych** [comment]
Indeed, there is a bug in `ct.tween` that prevents using UI time. The API used in the tutorial is also a bit dated. I've located the issue and will fix it in the next release. Right now, download my current version of `ct.tween` and replace yours with it:

[tween.zip](https://github.com/ct-js/ct-js/files/4790433/tween.zip)

You will also need to add `useUiDelta: true` to those `ct.tween.add` calls that are for UI elements.
