### ISSUE TITLE
Game export issues

### ISSUE THREAD

**Issue by helliandro** [ct-js/ct-js-old#199]
**Describe the bug**
When trying to export any game to Windows, the ct.js program does not stop processing the information and cannot complete the export. I wait an hour and nothing happens.
log: 
Exporting the project…
Adding desktop resources…
Preparing build metadata…
Baking icons…
Ready to bake packages. Be patient!
Building for Windows…

**To Reproduce**
1. Go to 'C:\Users\Helliandro\Documents\ct.js.v1.3.1.for.win32\win32'
2. Click on 'ctjs.exe'
3. Click on 'Browser'
4. Click on 'C:\Users\Helliandro\Documents\ct.js.v1.3.1.for.win32\win32\examples\JettyCat.ict'
5. Click on ct.IDE (Menu)
6. Click on 'Export for Desktop'
7. Select 'Windows' and Launch mode: 'Fullscreen'
8. Click on 'Export'

**Expected behavior**
I expected the program to export the game to a Desktop version.

**Screenshots (recommended)**
![rep4](https://user-images.githubusercontent.com/67524528/86354555-a119b700-bc3f-11ea-9f97-5c4066c2f080.png)
![rep3](https://user-images.githubusercontent.com/67524528/86354557-a24ae400-bc3f-11ea-9b0f-af496a4a2761.png)
![rep2](https://user-images.githubusercontent.com/67524528/86354560-a2e37a80-bc3f-11ea-92e2-a0df3f2e0792.png)
![rep1](https://user-images.githubusercontent.com/67524528/86354563-a414a780-bc3f-11ea-8584-a1956a55d320.png)

**Example project (strongly recommended)**
[JettyCat.ict.zip](https://github.com/ct-js/ct-js/files/4863985/JettyCat.ict.zip)

**Versions:**
 - OS: [Windows 7 - 32bits]
 - ct.js version 1.3.1

**Comment by CosmoMyzrailGorynych** [comment]
Cannot reproduce. Probably, you have connectivity issues or low connection speed. There is no means to track the progress of package downloads yet.

1. Make sure ct.js has access to the internet: it must not be blocked by antivirus or firewall. Your PC should be able to access electronjs.org.
2. Try again and output dev console (right-click + inspect element, then open Console and Network tabs and make a screenshot of each tab after running the packaging process for a couple of minutes or so.)
3. Leave ct.js open for a half an hour or so and see if there are any new errors or failed resource downloads in Console or Network tabs.

**Comment by helliandro** [comment]
I disabled the antivirus and the firewall to perform this action, but I still did not get results. I have a good internet speed, but the export still doesn't work. Thanks for the feedback!

**Comment by CosmoMyzrailGorynych** [comment]
What about the console and network tab? It may shed light on what is going on in ct while exporting.

![Peek 2020-07-03 09-57](https://user-images.githubusercontent.com/3174357/86412768-c8da4f00-bd13-11ea-941b-4a2c86bebc11.gif)

**Comment by CosmoMyzrailGorynych** [comment]
I'm closing this due to lack of feedback, and because the issue cannot be reproduced.
If someone has the same issue and has logs to share, write here and the issue will be reopened.

**Comment by BuslikDrev** [comment]
v1.7 у меня при экспорте просто закрывается программа.

**Comment by CosmoMyzrailGorynych** [comment]
@BuslikDrev, в таком виде эта информация абсолютно для меня бесполезна. У меня в версии 1.7 оба вида экспорта работают.

Вылеты на винде бывают обычно из-за двух вещей: из-за антивирусов или недостатка памяти (обычно котэ требуется 2 гига для комфортной работы сверх уже используемой системой).

**Comment by BuslikDrev** [comment]
> @BuslikDrev, в таком виде эта информация абсолютно для меня бесполезна. У меня в версии 1.7 оба вида экспорта работают.
> 
> Вылеты на винде бывают обычно из-за двух вещей: из-за антивирусов или недостатка памяти (обычно котэ требуется 2 гига для комфортной работы сверх уже используемой системой).

У меня win7 64x, 4 Gb оперативной памяти. Я попробую переустановить VisualC++ может из-за него конфликты какие-нибудь.

**Comment by MikeEngler** [comment]
I just had the same issue and it seems like my router blocked the app from reaching electronjs.org (or anything else).
Works fine when using my phone as wifi. So i think @helliandro you could try that if you still have the problem.
