### ISSUE TITLE
Unable to display tilesheet textures before placing a copy

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#206]
**Describe the bug**
When I create a room and try to place textures from a tile sheet, they don't appear until I have placed at least one copy.

**To Reproduce**
1. Create a room
2. Load a tile sheet and select a tile to paint with
3. Place a tile down
4. Nothing happens
5. Place a copy down and all the tiles you tried to place will appear.

**Expected behavior**
Tiles should appear.

**Screenshots (recommended)**
https://gyazo.com/f17e214dc823c933960738e21b6d4e05

**Versions:**
 - OS: Windows 10
 - ct.js version: v1.3.1

**Comment by CosmoMyzrailGorynych** [comment]
Ooooh thank youuuu!!!
I could never pinpoint the minimal steps to reproduce this bug. The bug is now fixed :)
