### ISSUE TITLE
Keyframing Support

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#208]
**Feature**
Add key framing support for types so you can define movement paths and such.

**Describe the solution you'd like**
Being able to add key frames to objects so they could like move back and forth in loop for example.

**Describe alternatives you've considered (optional)**
Hard coding movement for types.

**Comment by CosmoMyzrailGorynych** [comment]
You can use `ct.tween` for smooth values' transitions and skeletal animations for characters and other objects.
