### ISSUE TITLE
Disable Image Smoothing Ceases To Work

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#211]
**Describe the bug**
Disable image smoothing does not work.

**To Reproduce**
Open a project and enable image smoothing, then try to run your game. Your pixel art will be blurry.

**Expected behavior**
Should have disabled antialiasing.

**Screenshots (recommended)**
https://prnt.sc/twotap

**Versions:**
 - OS: Windows 10
 - ct.js version: 1.4

**Comment by CosmoMyzrailGorynych** [comment]
@yonderbread I can replicate your issue neither in a new blank project nor in the existing ones.

**Comment by CosmoMyzrailGorynych** [comment]
Please check your rendering settings again. If it really doesn't work, could you send the project's `.ict` file so I can look inside its rendering settings?

**Comment by yonderbread** [comment]
I found the issue, I needed to change my Fit To Screen settings to "Scaling with letterboxing" when in 1.3 I had it set to "Fast scaling with letterboxing". There should be a fix for this

**Comment by CosmoMyzrailGorynych** [comment]
Indeed, a CSS rule has gone missing during the v1.4 development. I can now reproduce the problem.
Fixed! :tada:
