### ISSUE TITLE
Copy content from embedded docs

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#216]
**Describe the current state of the problem**
I can't copy and paste text from the embedded documentation.

**Describe the solution you'd like**
Be able to copy text from the docs in the ct.js editor.

**Describe alternatives you've considered (optional)**
Opening up developer tools and copying text from there or just viewing the docs externally.

**Comment by CosmoMyzrailGorynych** [comment]
Fixed!
