### ISSUE TITLE
Export to Node.js project

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#218]
**Feature Idea**
An "open as node project" option in the project context menu.

**Describe the solution you'd like**
It would be cool if we could export the project as a node environment and modify things externally. I understand that a lot of the ct.js library is tightly connected with features in the editor and being stored in a save file, but once ways of being able to create objects that are only able to be created "visually" are able to be created programmatically, this should be an awesome addition.

**Comment by CosmoMyzrailGorynych** [comment]
Use cases?

**Comment by yonderbread** [comment]
Being able to have more control over building projects

**Comment by CosmoMyzrailGorynych** [comment]
For what? What is "control" for you? How would this help to create entities programmatically? What else does it solve? (You can all do it from within ct.js itself.)

If you need something in ct.js, tell about it, but don't create vague issues that tell nothing about **the root problem** and just move problems from ct.js to others' shoulders. The section about a problem in the issue template was there on purpose.
