### ISSUE TITLE
Cannot open ct.js directly on Ubuntu and Pop!_OS.

### ISSUE THREAD

**Issue by pennro-se** [ct-js/ct-js-old#221]
**Describe the bug**
Attempting to run a copy of ct.js (that is properly marked as executable) through a file mananger results in Ubuntu and Pop!_OS attempting to open it as a shared library instead of executing it.

**To Reproduce**
1. Download ctjs v1.4.1 for Linux x64 from either ctjs.rocks or itch.io (website or app) and extract it from the archive (if applicable)
2. Open the directory containing the application in a File Manager
3. Double Click on the `ctjs` file.

**Expected behavior**
The application should open when attemping to execute.

**Screenshots (recommended)**
![Screenshot from 2020-08-22 07-26-13](https://user-images.githubusercontent.com/471907/90958364-d628d580-e448-11ea-8683-a059ec2b92ea.png)
(This one is from Pop!_OS 20.04 using default DE and File Manager)

**Example project (strongly recommended)**
Not Applicable

**Versions:**
 - OS: Pop!_OS 20.04
 - OS Type: 64-bit
 - DE: Gnome 3.36.3
 - CT: 1.4.1

**Comment by pennro-se** [comment]
After some more digging, it doesn't look solvable on this end. We basically just need to wait for the maintainers of `file` to get around to it: https://bugs.launchpad.net/ubuntu/+source/file/+bug/1747711

Until then, workarounds include:
- Running ct.js from terminal
- Creating a bash script that basically just runs it directly like the previous step
- Create a desktop file to run it (again similar to the last two)
- Use the Itch.app to run it.

**Comment by CosmoMyzrailGorynych** [comment]
Nautilus won't open `xxx.desktop` files anymore. The way to solve this issue is putting ct.js in menus and on Desktop, which is done here: https://github.com/ct-js/ct-js-installer

**Comment by CosmoMyzrailGorynych** [comment]
Also, some sorcery with shebangs may take place there, but I have never researched this topic.

**Comment by amsam0** [comment]
The installer puts `.desktop` files in menus and desktops 🤔
