### ISSUE TITLE
Change "Export for desktop..." build directory

### ISSUE THREAD

**Issue by pennro-se** [ct-js/ct-js-old#223]
**Describe the current state of the problem**
Currently when exporting from the itch.io app, ct.js creates it's builds within folders it shouldn't be.
Itch.io currently installs apps into seperate folders within `~/.config/itch/apps/`.
When I export a game from ct.js, it creates it's builds in `~/.config/itch/apps/build/`.

Ignoring the fact that Itch should not be installing applications into a user's configuration files folder (they should be either using the `~/.itch/` folder they created for a universal solution [under linux] or within `~/.local/share/itch/` for a Gnome solution), locating the builds in a hidden folder under a different application's name is not the best move.

**Describe the solution you'd like**
Give the user the choice of where to place the builds, with the default being kept near the project's own directory.
Currently when a project is created, it both creates a `projectName.ict` file and a `projectName` folder to keep assets and scripts in, I suggest the default location for builds be project dependent and placed alongside that file and folder.

I suggest there also be an option on the "Export the Project" dialog of what directory to place the builds in, with that location saved for reuse within the project.

**Describe alternatives you've considered (optional)**
One alternative is to create a `"~/ctjs builds/"` folder within the user's home directory. It's less ideal but would be fair easier to access and less likely to cause confusion than `~/.config/itch/apps/build/`

**Comment by CosmoMyzrailGorynych** [comment]
Closed in v1.4.2
