### ISSUE TITLE
[catmod fs] Bring in-line with XDG Base Directory Specification

### ISSUE THREAD

**Issue by pennro-se** [ct-js/ct-js-old#224]
**Describe the current state of the problem**
Currently, by default, the "Desktop's file system" catmod uses `~/${author_name}/${project_name}` which has the potential to heavily pollute the user's home directory when ct.js becomes more popular.

**Describe the solution you'd like**
Instead it should follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/), which states the following locations should be used for various purposes.

`$XDG_DATA_HOME` as the base directory for [data files](https://en.wikipedia.org/wiki/Data_file). Defaults to `~/.local/share`
`$XDG_CONFIG_HOME` as the location for [configuration files](https://en.wikipedia.org/wiki/Configuration_file). Defaults to `~/.config`

This part is more subjective, but I do not think the author's name should be used in the path. Instead a separate "Organization Name" should be created and used in it's place. It's conceivable that in some organizations, there is not one specific author, but for indie development, I believe a lot of people would have the two be separate.

For an example. If I published a game called Vroom under a Organization called Ursid I would expect the data and config directories to likely be as follows:
`~/.local/share/ursid/vroom/`
`~/.config/ursid/vroom/`

**Describe alternatives you've considered (optional)**
I do not think that there is any good alternative to using the specification, however I can see the separation of author and organization being rejected. However if it does, I would suggest renaming it to "developer name".

**Additional context**
I have no idea if MacOS follows the specification and I would be surprised if Windows did. This is mainly for Linux.

**Comment by CosmoMyzrailGorynych** [comment]
Dare to make a PR?

**Comment by amsam0** [comment]
I can make one if needed.

**Comment by pennro-se** [comment]
I don't have a Windows or macOS system to test it on, but I've tested it on linux.

**Comment by amsam0** [comment]
I can test on windows and Mac.

**Comment by pennro-se** [comment]
I may have accidentally broken my branch with git. I'll need to fix it before PR

Edit: Nope, I just forgot which branch I was using.
