### ISSUE TITLE
PixiJs documentation popup toolbar icon is red

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#225]
**Describe the bug**

**To Reproduce**
1. Click on a hyperlink in the Ct.js docs for the Pixi.js docs
2. Look at your taskbar and you will notice the popup's icon is a red square.

**Screenshots (recommended)**
https://prnt.sc/u4gmdb

**Versions:**
Windows 10
Ct.js v1.4.1 (Nightly, latest as of today)

**Comment by CosmoMyzrailGorynych** [comment]
Pixi's docs don't have an icon/favico at all, and it is not ct.js' issue.
