### ISSUE TITLE
Location Marker Objects

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#227]
**Is your feature request related to a problem?**
Somewhat, I find it a bit much to have to define constants for coordinates for every single location in a room you want to be able to set triggers on and collision detection. Also having to make invisible textured sprites instead is kind of a crap way to do this.

**Describe the solution you'd like**
My solution to this would be to add markers to ct.js alongside Types and Copies, which would be an invisible object that the developer could place in a room and then later reference it in code. They would also be able to manipulate it during the game and move it around, scale it, etc...

**Describe alternatives you've considered (optional)**
Creating a huge script filled with coordinate sets.

**Comment by CosmoMyzrailGorynych** [comment]
I plan to add triggers and waypoints at #39, with copies' additional fields at #40. But this will happen in a not-so-close future.

**Comment by CosmoMyzrailGorynych** [comment]
Closing as it is actually a duplicate of #67
