### ISSUE TITLE
More failsafe methods

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#230]
**Describe the current state of the problem**
Some methods have optional arguments that significantly impact how they work. While coding, if these arguments get undefined though they were supposed to be not by a developer, it results in a confusing behavior.

Example:

* a game developer calls `ct.types.copy('Sausage', x, y, {}, this.uiRoom)`
* `this.uiRoom` is actually `undefined`
* `ct.types.copy` silently puts a new copy in `ct.room` as its fifth argument is not defined
* The world is now on fire.

**Describe the solution you'd like**
Split a number of methods into ones with a more narrow scope.

* [ ] `ct.types.copy(type, x, y, exts, room)` -> 
    * `ct.types.spawn(type, x, y, exts)`, and 
    * `ct.types.spawnInRoom(type, x, y, room, exts)`.
* [-] ~~`ct.rooms.append` ->~~ Rooms now have a checkbox "Is UI layer" at their settings tab, and I think there won't be any cases when one room should be used as a UI layer here and as a gameplay one there. Even if it does need to be so — extensions to the resque.
    * ~~`ct.rooms.appendWorld`~~
    * ~~`ct.rooms.appendUi`~~

(WIP, needs further observation)

**Describe alternatives you've considered (optional)**
Turning arguments into options object, which can be validated to catch such mistakes.

**Additional context**
—

**Comment by yonderbread** [comment]
This would definitely be helpful for making overlays.

**Comment by CosmoMyzrailGorynych** [comment]
Closed with https://github.com/ct-js/ct-js/commit/dbad7e3ef6486b7e883be3a3b1a31159e9ff1ac3 and https://github.com/ct-js/ct-js/commit/58e6fad9b48836ce21b2d5a298a262a2ceadef9d
