### ISSUE TITLE
Call external APIs while playing

### ISSUE THREAD

**Issue by alexis-anzieu-ssense** [ct-js/ct-js-old#233]
First of all, thanks for this awesome work!

**Is your feature request related to a problem?**
On a browser game, I would like to save my game online so I could replay it from whatever browser on whatever device

**Describe the solution you'd like**
Enabling AJAX or http library import to the IDE without the need to recompile the existing build

**Comment by CosmoMyzrailGorynych** [comment]
Excuse me, but your issue doesn't give sense to me.

Do you mean a feature for players so that they can upload their savegames to the cloud?

If no, could you elaborate on why do you need to import modules/recompile builds/recompile the engine?

**Comment by amsam0** [comment]
There might be a way to use google for saving games to the cloud.

**Comment by CosmoMyzrailGorynych** [comment]
Ok, I suppose that OP just wants to add an ajax library to the project. Their response to "Is your feature request related to a problem" was so gamedev-scoped that it derailed my train of thoughts into the void. Why an ajax lib is needed in [2020](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) is a good question but offtopic, so

You can add any library at Project tab -> Custom scripts.
Alternatively, you can add libraries at includes:
![изображение](https://user-images.githubusercontent.com/3174357/91908106-25032480-ecff-11ea-90a4-6e6e1b33d365.png)
And then add a `<script>` tag with akatemplate module.

**Comment by CosmoMyzrailGorynych** [comment]
@alexis-anzieu-ssense Please either confirm that your question is answered or provide additional info about your use case and feature request.

**Comment by AlexisAnzieu** [comment]
Oops yes it was not very clear sorry. So my question was more related to "is it possible to call an external API thanks to ajax or fetch native js" (to save game data somewhere else for instance). I was convinced that I aleady tried with custom script tab but ... it's working well now 🎉 . Thanks!

**Comment by alexis-anzieu-ssense** [comment]
Oops yes it was not very clear sorry. So my question was more related to "is it possible to call an external API thanks to ajax or fetch native js" (to save game data somewhere else for instance). I was convinced that I aleady tried with custom script tab but ... it's working well now 🎉 . Thanks!
