### ISSUE TITLE
Backup Button

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#234]
It would be awesome to have a button on the Project menu for backing up your project to a zip automatically. I know there's the recovery save file, but this would make it simpler to back up things before we make possibly-destructive changes to our games. Also a bonus would be having the option to load a backup automatically from inside the IDE.

**Comment by CosmoMyzrailGorynych** [comment]
@yonderbread Are you talking about this? Also, please do use issue templates.

![изображение](https://user-images.githubusercontent.com/3174357/92337541-8d3a7780-f0fe-11ea-9313-7d598d9bcba3.png)

**Comment by yonderbread** [comment]
Oh whoops sorry that did not pop out at me. And ok I will keep that in mind.
