### ISSUE TITLE
Investigate usefulness of pixi-layers

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#237]
**Describe the current state of the problem**
[`pixi-layers`](https://github.com/pixijs/pixi-display) may provide performance boosts (*may*), and will make ct.js compatible with some poopy effects like https://github.com/pixijs/pixi-lights

**Describe the solution you'd like**

* Add a branch that uses pixi-layers instead of manual scene sorting
* If it provides noticeable benefits, or at least doesn't make stuff worse, merge it into v2 branch.

**Describe alternatives you've considered (optional)**
—

**Additional context**
—

**Comment by CosmoMyzrailGorynych** [comment]
Oh no, it is needed for not poopy lighting, too: https://pixijs.io/examples/#/plugin-layers/lighting.js (triaged; can make a workaround with RenderTexture, though)

**Comment by yonderbread** [comment]
This would be good for game UI too

**Comment by CosmoMyzrailGorynych** [comment]
@yonderbread this has nothing to do with UI, and ct.js already has all the API to work with UI layers.
