### ISSUE TITLE
Add an option to manually set ct.js' data directory. Without it, users with remote home folders will get errors.

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#238]
**Describe the bug**
Ct.js exports game data and tries to create projects inside `~/ct.js` folder.

**To Reproduce**
1. Work in an environment with folder redirection when a home directory is on a network drive.
2. Launch ct.js
3. Try creating a project (nothing happens)
4. Load an example project
5. Try exporting it
6. See the error `Error: ENOENT, no such file or directory, mkdir '\\?`

**Expected behavior**
Ct.js should fallback to other locations and allow users to manually choose folder where the data is saved.

**Screenshots (recommended)**

![изображение](https://user-images.githubusercontent.com/3174357/94511665-152f1f80-026e-11eb-9a2a-f00ad60cfd93.png)

The profile name contains lowercase latin letters only. We can clearly see that ct.js is placed in a desktop folder, and the path of this folder does not overlap 

**Example project (strongly recommended)**
Not applicable

**Versions:**
 - OS: Windows 10
 - ct.js version 1.4.2

**Comment by yonderbread** [comment]
looking forward to this being implemented
