### ISSUE TITLE
Example Projects Tab Has No Examples

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-old#245]
**Describe the bug**
Ct.js Example projects do not show up in Linux.

**To Reproduce**
1. Install Ct.js with the installer
2. Open Ct.js and go to the Examples tab

**Expected behavior**
A list of example projects should appear.

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/33736622/98837667-13718380-23f8-11eb-94c5-37886ae464d0.png)

**Versions:**
 - OS: Pop!_OS 20.10
 - ct.js version: v1.5.0

**Comment by yonderbread** [comment]
I feel like this issue should be added onto [the installer repo](https://github.com/ct-js/ct-js-installer).

**Comment by CosmoMyzrailGorynych** [comment]
Closed by https://github.com/ct-js/ct-js/pull/357
