### ISSUE TITLE
'Capture!' module doesn't work.

### ISSUE THREAD

**Issue by HLenin** [ct-js/ct-js-old#252]
**Describe the bug**
It stops ('stops' not 'pauses') and lags my game. It shows an error saying: `t.updateTransform` is not a function. I also tried this on the builded version for windows too, it doesn't work. Also, the 'Capture' module doesn't have the 'warning' or 'issue' symbol on it.

**To Reproduce**
1. Place this code in a type:
```
if(ct.actions.Screenshot.pressed){ //The screenshot action is 'C' key
   ct.capture.screen();
}
```
2. Put the type with the code in a room
3. Start the game in a room where that type is in
4. Press 'C' //Again, this is the screeshot action
5. Shows error

**Expected behavior**
I will be prompted to save the image.

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/66825478/101419851-db445e80-392b-11eb-91fd-ad811c81a407.png)
![image](https://user-images.githubusercontent.com/66825478/101420148-8a813580-392c-11eb-8341-c7c8d8a1c2eb.png)

**Versions:**
 - OS: Windows
 - ct.js version: v1.4.2

**Comment by CosmoMyzrailGorynych** [comment]
@HLenin Update to v1.5: https://github.com/ct-js/ct-js/releases/tag/v1.5.0
