### ISSUE TITLE
Removal of Telemetry by Google Services

### ISSUE THREAD

**Issue by Tall-Lobster** [ct-js/ct-js-old#255]
**Is your feature request related to a problem?**
It is really annoying when exporting a game into web mode that google analytics are automatically included.
Tag any related issues here.

**Describe the solution you'd like**
Allow the user to have the options of what telemetry features to include/not include

**Describe alternatives you've considered (optional)**
I was thinking of removing the code for google analytics but I am not sure if it also included in PixJS

**Additional context**

**Comment by CosmoMyzrailGorynych** [comment]
@Tall-Lobster, ct.js does not include google analytics in exported games — it is at the very least illegal. Neither includes any tracking Pixi.js.

If you are sure that you've found tracking code in ct.js' exports, please identify where is the code that injects these analytic trackers.

If you deploy games on itch.io, GameJolt, or such, these platforms may inject google analytics by themselves. Try setting up a local web server and see whether the issue persists there (debugging a game in an external browser counts as a web server).

**Comment by Tall-Lobster** [comment]
Dear @CosmoMyzrailGorynych;
thanks for the help. I will try deploying the game. However could you point me to some instructions to run the game, since when I open the index.html file, it doesn't run the game. Also I think the first time i saw the google analytics is when using the launch aspect of ct.js... but now I don't see it???

I had to run the game in Falkon Browser before I could see the game running, and now I don't see any google analytics...

So I am gonna apologize for any inconvenience this has caused you.

**Comment by Tall-Lobster** [comment]
There is something I realized after looking over ct.js.

You built ct.js using NW.js, which using parts of google chrome. In this case, from the knowledge I have acquired in the past few years, that means the application (without intention) will be using chromium aspects which those have been linked with Telemetry. So in this case, the games produced do not collect information unless you built an executable to run on each platform respectively.

**Comment by CosmoMyzrailGorynych** [comment]
Don't mix up Google Chrome and Chromium. Chromium is an open-source browser without tracking, and nw.js and electron are based on it, not on Google Chrome.

**Comment by CosmoMyzrailGorynych** [comment]
> could you point me to some instructions to run the game, since when I open the index.html file, it doesn't run the game.

Ct.js' web builds need a web server. Web build. Web server. Okay?
Ct.js runs a web server for you, and opening a game in an external browser from within ct.js (see the buttons at the bottom of the debugger) works.

If you doubt the ct.js' server, you can try any other static web server. For example, with ["here"](https://www.npmjs.com/package/@vivaxy/here).
