### ISSUE TITLE
Instructions to Compiling Ct.js (ARM architecture)

### ISSUE THREAD

**Issue by Tall-Lobster** [ct-js/ct-js-old#256]
**Is your feature request related to a problem?**
I want to start using a raspberry pi for game development as well as software development, however I don't know how to build ct.js to build games to run on linux and to develop games on linux.
Tag any related issues here.

**Describe the solution you'd like**
Step by step instructions (with pictures if possible) to build ct.js, including the required libraries

**Describe alternatives you've considered (optional)**

**Additional context**

**Comment by CosmoMyzrailGorynych** [comment]
@Tall-Lobster if your Raspberry Pi runs on an ARM processor (AFAIK they do), then you will have a hard time preparing ct.js to run on it. Games made in ct.js will run without extra steps, though.

If you have a regular processor (not ARM), see [this paragraph](https://github.com/ct-js/ct-js#forking-and-installing-the-dev-environment) in the readme, plus "Running ct.js from sources" next to it. But usually, people download it from [releases](https://github.com/ct-js/ct-js/releases) or [itch](https://comigo.itch.io/ct).

If you do need to run ct.js for ARM, then everything is more complicated. Shortly, we support all the platforms officially supported by nw.js, the framework on top of which ct.js is built. And ARM is not in this list.

You will need to use an [unofficial distribution of nw.js for ARM](https://github.com/LeonardLaszlo/nw.js-armv7-binaries). Use the latest version possible. Ideally, you need just these steps:

1. Run preparation steps from [that same paragraph](https://github.com/ct-js/ct-js#forking-and-installing-the-dev-environment) from readme;
2. Download the ARM binaries and unpack them inside the cloned ct.js repo;
3. Run `gulp build` to build the sources;
4. Run `./nw --use-gl=egl --ignore-gpu-blacklist --disable-accelerated-2d-canvas --num-raster-threads=2` inside the cloned repo, as specified in this [readme](https://github.com/LeonardLaszlo/nw.js-armv7-binaries#instructions-for-running-your-nwjs-application-on-linux-armv7).

And you should get a working instance of ct.js. In theory. In practice, I doubt it was done before, and no one knows what obstacles you will face. Do ask questions though, I will try to help as I can. (I don't have an ARM machine, though, and won't be able to try all this out by myself.)

**Comment by Tall-Lobster** [comment]
OH my bad I forgot to let you know. I have already used this game editor (in reality you should have called it a game engine) to make my own unfinished game for a course. I really liked it so that is why I was wondering how you built it so I can figure out how to build it for the Raspberry Pi. Thanks for the instructions!

**Comment by CosmoMyzrailGorynych** [comment]
@Tall-Lobster let me know how it goes. If it works for you, we will know that there is a way of distributing ct.js for ARM architectures.

**Comment by Tall-Lobster** [comment]
Dear @CosmoMyzrailGorynych 

Sadly turns out the raspberry pi 4 is armv8 not armv7 so I cannot use this tutorial. I tried looking for anyone who built armv8 but no success. So in this case this will work on the old raspberry pi 3, but sadly I have the raspberry pi 4 that I wanted to use for development. That also means the games exported to run without a browser can't run on the raspberry pi 4.
