### ISSUE TITLE
ct.mouse.hovers is triggered permanently instead of per-frame

### ISSUE THREAD

**Issue by mvxt** [ct-js/ct-js-old#261]
**Describe the bug**
I have multiple copies and am trying to perform an action only for the specific copy the user clicks on. I do this check by using the following:

```
if (ct.actions.MYACTION.pressed && ct.mouse.hovers(this)) {
    // ...etc.
}
```

However, it looks like `ct.mouse.hovers(this)` returns true if your mouse has hovered over this copy _**at any point during the lifetime of the game.**_

**To Reproduce**
1. Create an action and set it to left mouse click.
2. Create a Type using any texture you want.
2. Place multiple copies of the Type into a Room.
3. Paste the snippets of code shown below.
4. Start the game in debug. Make sure you don't hover over any copies to start.
5. Pick any copy and click on it. Observe the console correctly printing position and integer.
6. Then hover over another copy. Observe how not only did your current copy you clicked/hovered on change, but also the one you previously clicked, but are not hovering over anymore.

On Create:
```
this.current = 0;
```

On Step:
```
if (ct.actions.YOUR_ACTION.pressed && ct.mouse.hovers(this)){
    this.current++;
    console.log(this.position.x + "," + this.position.y + ": " + "this.currentState);
}

this.move();
```

**Expected behavior**
I would have expected `ct.mouse.hovers(this)` to return true _**only if the mouse pointer is currently hovering over the current copy**_, false otherwise.

**Screenshots (recommended)**
After clicking first square (X marks which square I clicked):
![Screen Shot 2020-12-30 at 2 43 42 PM](https://user-images.githubusercontent.com/2441695/103382935-21fe2200-4aae-11eb-9857-e8e2a2fa8184.png)

After clicking second square:
![Screen Shot 2020-12-30 at 2 45 05 PM](https://user-images.githubusercontent.com/2441695/103382947-2aeef380-4aae-11eb-9bae-b747c7e41f25.png)

After clicking 3rd square:
![Screen Shot 2020-12-30 at 2 46 30 PM](https://user-images.githubusercontent.com/2441695/103382952-2e827a80-4aae-11eb-9078-c18d88bc77f9.png)

**Versions:**
 - OS: macOS Catalina 10.15.7
 - ct.js version: 1.5.1

**Comment by mvxt** [comment]
If this isn't a bug:

- What is the better/correct way to check per-copy click? It does seem inefficient for _**every**_ copy of this type to be running this check.
- Can we modify the documentation of `ct.mouse.hovers` to explicitly declare scope? E.g., "Returns `true` if the mouse hovers over a given `copy` _**at any point during the lifetime of the game**_."

**Comment by dtgreene** [comment]
I wasn't able to reproduce this.  I copied your example but it worked as expected 😕 .  I clicked the first object, then the one below it, then the first again.  It only logged one message each time.

![image](https://user-images.githubusercontent.com/24302976/103396384-95c51c80-4af8-11eb-968e-38811e0b6d91.png)

I'm on Windows 10.  Maybe something else going on?

**Comment by mvxt** [comment]
🤔 So, here's the weird part. I scraped together a new project and was also unable to recreate the issue. But I've combed over my whole working project multiple times now and just cannot figure out what is causing this.

I've included a ZIP file with my project here - maybe you'll spot something I missed??

[MusicMesh.ict.zip](https://github.com/ct-js/ct-js/files/5757025/MusicMesh.ict.zip)

**Comment by dtgreene** [comment]
I downloaded it and checked.  It's because your collision mask is 512x512 but your sprites are 128x128.  So they are overlapping each other causing you to click multiple at a time  :)

**Comment by mvxt** [comment]
🤦  Thank you for finding that. I don't know when that was changed or how it got that way but thank you! I'll close the issue.
