### ISSUE TITLE
After running game, application must be force quit

### ISSUE THREAD

**Issue by oaklandgit** [ct-js/ct-js-old#263]
**Describe the bug**
The app is unable to quit using File > Quit or Cmd-Q. Instead it must be forced quit.

**To Reproduce**
1. Launch the ctjs app
2. Load any project
![image](https://user-images.githubusercontent.com/421615/103446195-b5139500-4c31-11eb-9c77-c4cba6cca1a9.png)
3. Launch the project
![image](https://user-images.githubusercontent.com/421615/103446202-c9f02880-4c31-11eb-97c4-4a0a0b40ab6b.png)
4. Quit while project is running using File > Quit or Cmd-Q.
![image](https://user-images.githubusercontent.com/421615/103446218-fc9a2100-4c31-11eb-931c-80a440202e90.png)

5. The game quits, but NOT the full application
6. Clicking File > Quit or Cmd-Q again does nothing.
7. App remains open. Must force quit
![image](https://user-images.githubusercontent.com/421615/103446249-5dc1f480-4c32-11eb-941e-f40e933789f8.png)

**Expected behavior**
The application should quit on File > Quite or Cmd-Q

**Screenshots (recommended)**
(see above)

**Example project (strongly recommended)**
Happens with all projects including the Dungeon Crawler Tutorial (as a known entity)

**Versions:**
 - OS:  Big Sur (11.0.1)
 - ct.js version 1.5.0

**Comment by CosmoMyzrailGorynych** [comment]
@oaklandgit update to v1.5.1 and try to reproduce it again.

**Comment by oaklandgit** [comment]
Thank you @CosmoMyzrailGorynych . That seemed to have done the trick!
