### ISSUE TITLE
Transtion in hindi

### ISSUE THREAD

**Issue by vivek80801** [ct-js/ct-js-old#265]
Can I translate documentation in **Hindi** ?

**Comment by CosmoMyzrailGorynych** [comment]
@vivek80801, yup, you can. See [ct-js/docs.ctjs.rocks](https://github.com/ct-js/docs.ctjs.rocks) repo and how "ru" locale has been added.

**Comment by vivek80801** [comment]
@CosmoMyzrailGorynych Thanks for giving an opportunity.
