### ISSUE TITLE
MacOS build missing examples

### ISSUE THREAD

**Issue by HoverBaum** [ct-js/ct-js-old#268]
**Describe the bug**

The MacOS bundle does not contain an examples folder.

**To Reproduce**

1. Download the macOS version from itch.io at https://comigo.itch.io/ct
2. Check for an examples folder 🗂
3. No such folder exists 😔

Also: No examples are shown when opening the application.

**Expected behavior**

Examples folder with assets for Tutorials should be present.

**Comment by amsam0** [comment]
I believe it does exist, but it’s hidden in the .app

**Comment by markmehere** [comment]
This should be fixed by #286

**Comment by CosmoMyzrailGorynych** [comment]
> This should be fixed by #286

@markmehere Can you confirm this? App is packaged by calling `gulp packages`.

**Comment by markmehere** [comment]
I'm pretty sure. We will know for sure in 1.7.1. Happy to run a nightly build little hesitant to run `gulp packages` because of the issue I specified in the pull request. Setting back up my Finder is a bit of a hassle. 🤕

**Comment by markmehere** [comment]
I didn't realise there were nightly builds available here:

https://comigo.itch.io/ct-nightly

By my running of them the problem is solved but have a look yourself @HoverBaum - devs are always pretty bad at testing their own fixes.
