### ISSUE TITLE
More inputs in copies' properties and type editor

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#269]
**Is your feature request related to a problem?**
More settings to tweak copies' look and behavior mean less fiddling with code and a more visual workflow, which is good. Each item in the list below solves one of the tiny problems.

**Describe the solution you'd like**

Copies' properties when you select them in the room editor:

- [x] Adding custom, user-defined properties to individual copies. These should write to copy's `exts` object. This allows customizing the behavior of individual copies without creating new types.
- [x] Opacity, visibility in a room, and tint controls, and a depiction of these properties in the room editor. Can be used for triggers and level design. Depends on #39 

Type editor:

- [x] "Play animation" checkbox and "Animation speed" field. Should also explain (in a tooltip, I think) how the animation speed is computed and how to change this property in code, as well as stop/play animation.

**Comment by oaklandgit** [comment]
Some additional thoughts in #280
