### ISSUE TITLE
Black bar covering UI in Texture tab

### ISSUE THREAD

**Issue by oaklandgit** [ct-js/ct-js-old#276]
**Describe the bug**
A black bar covers the UI in Texture tab. It can often be fixed by resizing the window, but not always.

**To Reproduce**
1. Go to Textures tab
2. Resize window
3. Black bar appears, obscuring content

**Expected behavior**
No black bar

**System information report**
Ct.js v1.6.2 😽 (packaged)

NW.JS v0.51.2
Chromium v88.0.4324.182
Node.js v15.8.0
Pixi.js v5.1.2

WebGL available
WebGL vendor Intel Inc.
WebGL renderer Intel(R) Iris(TM) Plus Graphics OpenGL Engine
OS darwin x64 // Darwin 20.3.0

**Screenshots (recommended)**
<img width="1300" alt="Screen Shot 2021-04-09 at 4 35 40 PM" src="https://user-images.githubusercontent.com/421615/114250246-f95db200-9951-11eb-96cb-b34d27db3f42.png">

**Example project (strongly recommended)**
(Happens using the sample files also, so I don't believe it's related to my particular project.)

**Comment by CosmoMyzrailGorynych** [comment]
So it happens exclusively on the Textures tab?? Not in the room editor, and neither in the particle system editor?? This is weird.
All in all, it is either a driver- and hardware-specific bug or chromium's issue, and not ct.js' code, so I'm at little power here. Searching through nw.js' issues and the web didn't help, either.

Have you ever met such issues in other browsers, especially Chrome/Chromium/Opera?

If possible, update graphics drivers for your OS. If it is not possible or if it doesn't help, try running ct.js from sources at v1.x branch and using a newer nw.js version [at this line](https://github.com/ct-js/ct-js/blob/v1.x/gulpfile.js#L48) (it is 0.52.2 as of the time of writing). Tell us if you were able to solve this issue.

**Comment by oaklandgit** [comment]
I see it actually happens on other tabs as well. I haven't seen this issue before, and I use Chrome daily.

**Comment by markmehere** [comment]
Anyone looking at this also check out #286 - there's a black box issue there that **was fixed** by bumping nwVersion as explained in the pull request: bugs with the graphics acceleration are common in Chromium - even making it to Chrome proper from time-to-time. To see whether graphics acceleration is the root cause you can disable GPU. I think by adding `argv: '--disable-gpu'` to line 329 of `gulpfile.js` so it now reads:

```
    const nw = new NwBuilder({
        files: nwFiles,
        version: nwVersion,
        downloadUrl: nwSource,
        manifestUrl: nwManifest,
        platforms: [processToPlatformMap[platformKey]],
        flavor: 'sdk',
        argv: '--disable-gpu'
    });
```

I used to know the exact code for sure. But I've forgotten it now. This code works during dev runs not sure if that is where you specify the arguments for builds. Also not convinced we should blanket disable GPU acceleration for builds.

**Comment by markmehere** [comment]
I mean the screenshots of the two issues look really really similar. 😄

**Comment by markmehere** [comment]
Oh wait @oaklandgit was on Mac OS X too. Then #286 is more likely than not the fix.

**Comment by markmehere** [comment]
I didn't realise there were nightly builds available here:

https://comigo.itch.io/ct-nightly

By my running of them the problem is solved but have a look yourself @HoverBaum - devs are always pretty bad at testing their own fixes.

**Comment by markmehere** [comment]
I didn't realise there were nightly builds available here:

https://comigo.itch.io/ct-nightly

By my running of them the problem is solved but have a look yourself @oaklandgit - devs are always pretty bad at testing their own fixes. The issue I saw was in the fonts (see my pull request).
