### ISSUE TITLE
Duplicate or "fork" project from Home screen

### ISSUE THREAD

**Issue by oaklandgit** [ct-js/ct-js-old#277]
**Is your feature request related to a problem?**
I want to be able to, with one click, "branch" a project so I can safely experiment, while keeping my original intact.

**Describe the solution you'd like**
It would be nice to be able to simply click "duplicate" from a project preview on the home page, somewhat how repl.it or github work. The metaphor of "duplicate" or "fork" is appropriate for a game engine such as this.

**Describe alternatives you've considered (optional)**
I can copy the directory and .ict file of my project from within the file system. This works, but it's cumbersome.

**Additional context**
None.

**Comment by CosmoMyzrailGorynych** [comment]
A good idea! Especially for example projects. I think "clone" is a more general and suitable verb here.

**Comment by oaklandgit** [comment]
Sure, "Clone" works. Thanks!
