### ISSUE TITLE
Ability to edit custom parameters of a copy from within the room editor.

### ISSUE THREAD

**Issue by oaklandgit** [ct-js/ct-js-old#280]
**Is your feature request related to a problem?**
When creating a Type, you often need variants for any particular instances (Copies) of that type. It's clear how to pass parameters to Copies in code (as in the below example from the documentation)…
```
ct.types.copy('UI_Message', 35, 65, {
    message: 'Your warriors have engaged the enemy!',
    type: 'alert'
}, uiLayer);
```
…but that doesn't take full advantage of having a Level Editor, in which you would define such parameters while placing game objects into the level. 

**Describe the solution you'd like**
I would like the ability to edit custom parameters of a copy from within the room editor, in a way similar to how I would adjust default parameters such as position and scale.

I'd expect to be able to add the parameters (aka Fields) I would like to have exposed to be in the Level Editor in the Types tab, probably beneath Name, Depth, Collision Group, etc.

**Comment by oaklandgit** [comment]
And sorry, just seeing that this is likely a dupe of https://github.com/ct-js/ct-js/issues/269

**Comment by CosmoMyzrailGorynych** [comment]
@oaklandgit this feature was added in v1.7; you can right-click a copy and click "Custom properties". There you can set strings, boolean values, numbers, and arrays.

**Comment by CosmoMyzrailGorynych** [comment]
> I'd expect to be able to add the parameters (aka Fields) I would like to have exposed to be in the Level Editor in the Types tab, probably beneath Name, Depth, Collision Group, etc.

That's more about another idea I have in my head — having a UI to describe user-defined properties shown in other UI views. I don't remember in particular where I described it... But it better uses #203 class inheritance as its basis. Custom predefined fields are useful for rooms, type subclasses, and copies.

**Comment by oaklandgit** [comment]
> @oaklandgit this feature was added in v1.7; you can right-click a copy and click "Custom properties". There you can set strings, boolean values, numbers, and arrays.

Yup! Found it after I saw the related suggestion. I might submit an addition to the documentation repo.
