### ISSUE TITLE
MacOS - Invisible buttons over top nav bar 

### ISSUE THREAD

**Issue by limitlis** [ct-js/ct-js-old#293]
**Describe the bug**
After a while when there appears to be some invisible obstruction over top of the main nav bar. Upon trying to inspect the invisible element it appears to be hidden inputs for screenshot and something else (import maybe? It opens up a file select modal looking for .icts). 

**To Reproduce**
I don't really have repro steps yet. But at some point during normal usage those buttons transition over top of leading to accidental clicking.

**Expected behavior**
The invisible buttons shouldn't be there.

**System information report**
Ct.js v1.7.0 😽 (packaged)

NW.JS v0.51.2
Chromium v88.0.4324.182
Node.js v15.8.0
Pixi.js v5.1.2

WebGL available
WebGL vendor Intel Inc.
WebGL renderer Intel(R) Iris(TM) Plus Graphics 655
OS darwin x64 // Darwin 19.6.0

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/868862/125102671-65a29b80-e090-11eb-8ee6-c1ee9d9aff3d.png)
![image](https://user-images.githubusercontent.com/868862/125102696-6d624000-e090-11eb-9a5c-5df43488009d.png)

**Comment by CosmoMyzrailGorynych** [comment]
Will be fixed in the next release, thanks
