### ISSUE TITLE
Duplicating Type Menu Bug

### ISSUE THREAD

**Issue by Tiger-The-Cat** [ct-js/ct-js-old#298]
When one tries to duplicate a type, they get this menu.
![image](https://user-images.githubusercontent.com/70044734/129424541-b7734e0e-2cae-418e-b4b5-b4442e75f56a.png)
For some reason, the "Okay\Duplicate\Copy" button says "Delete" instead.
Thanks!

**Comment by SaberTooth-Studios** [comment]
lol

**Comment by CosmoMyzrailGorynych** [comment]
Can't reproduce or find the source of the issue 🤔
The "Delete" label can be a non-reset property from another modal, but other delete dialogues do reset them after deleting an asset.
If you find the steps to reproduce the bug, write them here.
