### ISSUE TITLE
"All unsaved changes will be lost" does not appear when closing 

### ISSUE THREAD

**Issue by QuickBanjo** [ct-js/ct-js-old#302]
### Describe the bug
When taking various actions in the IDE that would discard outstanding changes, such as opening another project, a confirmation modal appears, saying something along the lines of "All unsaved changes will be lost". The modal would have options to continue the action or cancel.

When closing the IDE via the OS, this modal does **NOT** appear.

### To Reproduce
On version 1.7.0,

1. Open Ct.js.
2. Open any project with at least one non-texture asset.
3. Open the non-texture asset in its respective editor.
4. Make a change.
5. Click "Apply" or "Done", _without_ saving.
6. Close the Ct.js window via your OS, e.g. click on the big 'X' in the upper-right/upper-left corner, as you would any other app.
7. **Actual behavior:** When the IDE is closed, nothing else happens.

This appears to be occurring on both Windows and Linux.

### Expected behavior
When the IDE is closed with unsaved changes, the described confirmation modal appears.

### System information report
Ct.js v1.7.0 😽 (packaged)

NW.JS v0.51.2
Chromium v88.0.4324.182
Node.js v15.8.0
Pixi.js v5.1.2

WebGL available
WebGL vendor AMD
_[redacted]_
OS linux x64 _[redacted]_

### Screenshots
Expected warning when closing the IDE. This example occurs when clicking "Open Project".
![close-ide-expected](https://user-images.githubusercontent.com/93800914/140631847-dfeb5232-e70c-413d-ab13-01530c392a32.png)

### Example project
n/a. Should occur with any project with unsaved changes.

**Comment by CosmoMyzrailGorynych** [comment]
Closed in https://github.com/ct-js/ct-js/commit/5f2c4a435ef3fc58a57b69664aff90c5d192201c.
Also fixes the situation where ct.js asks for your confirmation to close even if you've just opened a project.
