### ISSUE TITLE
Button to discard pending changes

### ISSUE THREAD

**Issue by QuickBanjo** [ct-js/ct-js-old#306]
### Description
As a user, I want to be able to cancel changes I've made to an asset if I have not yet clicked the `Apply` or `Done` button, because I want to be able to aggregate related unsaved changes on open assets, **AND** I want these changes not to be saved with the rest of the project until I'm certain I want them saved.

- [x] Update button labels
- [ ] Change the in-memory editing behavior, and Update behavior of `Apply` accordingly
- [ ] Add `Discard`
- [ ] Updating project saving

### Current Behavior
Under each editor, when an asset is open, we currently have a button stating `Save`, `Apply`, or `Done`. The button displayed depends on the kind of asset.

Under all three cases, most changes made to an asset are immediately reflected in the project in volatile memory. So if you make a change, switch to another tab, then click the 💾 (disk) button to save the whole project, the changes made in the editor are written to disk.

In addition, the behavior of the `Save`, `Apply`, and `Done` buttons, as they appear in the editors, is equivalent: they all simply close the editor. Changes made are reflected in volatile memory, but are **NOT** written to disk, just as if you had switched to another tab.

In all three cases, it is impossible to "undo" or "discard" changes made in the editor (except in the script text editor, thanks to Monaco), and it appears to be impossible to make any changes at all without all such changes being written to disk upon clicking 💾

This means, if we want to tinker around with some parameters to see how everything looks put together, but we end up not liking it, we _cannot_ revert the asset to the previous state without reloading our project. This "fear" of tinkering greatly diminishes the usability and intuitiveness of ct.js.

### Solution Requirements
We will update the button labels:
- For each editor, the button label that corresponds to closing the editor **MUST** be the same across all editors.
- This common label **SHOULD** appear as "✅ Apply".
- This button, when hovered over, **SHOULD** display the shortcut for that button as a rollover tip.

We will change the in-memory editing behavior, and the behavior of `Apply`:
- Changes made in an editor, since the last time `Apply` was clicked for that asset, **MUST NOT** be reflected in the volatile project state, until `Apply` is clicked.
- These changes **SHOULD** be written to a copy of the asset being edited.
- When `Apply` is clicked, these changes **MUST** be reflected in the volatile project state.
- When `Apply` is clicked, these changes **MUST NOT** be reflected in the persistent project state, until the project is saved at a later time.
- If there are such outstanding changes, there **SHOULD** be an indicator on the editor's tab denoting that there are outstanding changes. This indicator **SHOULD** be an asterisk * to the right of the tab label, e.g. "✨ FX*".

We will add a `Discard` button:
- For each editor, there **MUST** be a button somewhere that clearly indicates "discard", "undo", or "revert" functionality.
- This button **SHOULD** be an 'X', in the opposite corner from `Apply`, or in the upper-right hand corner otherwise (upper-left if there is a handedness option and it is set to be on the left).
- This button **SHOULD NOT** be located very close to other controls, and other controls **MAY** be moved slightly to make room for the new button.
- Clicking `Discard` **MUST** close the editor.
- Changes made in the editor before closing, since the last time `Apply` was clicked for that asset, **MUST NOT** be reflected in the volatile or persistent project state.
- If there are outstanding changes that would be discarded, clicking `Discard`, by default, **MUST** display a confirmation/cancel modal notifying the user that changes are outstanding, and that their changes will be lost. This modal **SHOULD** have an option to continue discard/"ok".
- The user **MAY** have the option to disable this modal.

We will update project saving functionality to account for outstanding changes:
- If the user saves the entire project, e.g. via 💾, after clicking through any modals or warnings, the app **MUST** reflect all outstanding changes made, similarly to if `Apply` was clicked in each individual tab before saving.
- If the user saves the entire project in this way, all previously outstanding changes in the app **MUST** be reflected in the persistent project state, as expected when saving a project.
- Prior to saving the project in this way, the app **SHOULD** display a confirmation/cancel modal notifying the user that changes are outstanding, and that continuing will _apply all outstanding changes_. The option to continue **SHOULD** be labelled "Apply & Save".

A reminder:
- All labels and other strings **SHOULD** be translated to all languages under `app/data/i18n`, when practical.

### Concerns
Development on the new tab-based interface should ensure that this behavior still functions as expected in the new interface.

### Considered Alternatives
**DO NOT** use without maintainer permission. We have considered the following options, but these were inconsistent with maintainers' approved plan:
- Have changes still occur in place, and have Done/Revert buttons instead, closer to the current behavior.
- Save without applying, simply show warning that outstanding changes were not saved.
- Show modal upon saving, and in addition to "Apply & Save" option, have a "Save Without Applying" option.
- Make `Discard` appear with the text "Discard", and place it near `Apply`, and give it a similar size.

### Additional context
Current solution largely approved by @CosmoMyzrailGorynych  on Discord:
>...if file-based project structure will come out someday, it is better to do this transition [to a transactional model] now. [I prefer] writing to a local object's copy and committing it with a button click. The label is "Apply", and perhaps for now the "Discard" button will be a small cross in the top-right corner or something. It won't fit every asset editor, and yet I don't want any fat extra buttons...
>
>...[of outstanding changes modal] better just "Apply & Save" and "Cancel"

**Comment by CosmoMyzrailGorynych** [comment]
I still don't know how to incorporate it into UI nicely. Maybe someone will come up with nice mockups. Otherwise, it will be postponed to the times where there will be a tabbed, multi-asset interface.

**Comment by CosmoMyzrailGorynych** [comment]
For the record, this issue is handled as part of #48 and is, in fact, complete indeed.
