### ISSUE TITLE
FX tab: can't group fx's

### ISSUE THREAD

**Issue by Shadowblitz16** [ct-js/ct-js-old#333]
**Describe the bug**

**To Reproduce**
1. Go to `fx` tab
2. Click on Show ungrouped
3. Drag player-thrust to player group
4. See nothing happens

**Expected behavior**
The particle fx should be moved into the group

**System information report**
Ct.js v2.0.1 😽 (packaged)

NW.JS v0.59.0
Chromium v96.0.4664.55
Node.js v17.1.0
Pixi.js v5.3.11

WebGL available
WebGL vendor AMD
WebGL renderer AMD RENOIR (DRM 3.41.0, 5.13.0-35-generic, LLVM 12.0.0)
OS linux x64 // Linux 5.13.0-35-generic

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/2453707/161397446-c33164ed-0683-4ab2-8da3-9541e90fe67f.png)

**Example project (strongly recommended)**
[AstroWars.ict.zip](https://github.com/ct-js/ct-js/files/8403223/AstroWars.ict.zip)

**Comment by CosmoMyzrailGorynych** [comment]
Fixed.
Can be applied for older projects in Nightly versions (that are still counted as v2.0.1) with `applyMigrationCode('2.0.2');` command in the console.
Works as is in newer projects.
