### ISSUE TITLE
Copy's direction reverts to 0 after speed change

### ISSUE THREAD

**Issue by MorenoIgor** [ct-js/ct-js-old#334]
I'm not sure if this is a bug or some intended behavior, but it is game-breaking.

**Describe the bug**
Whenever a copy's speed is changed via this.speed, its direction property is reverted to 0 after the speed change. If direction is not changed manually once again, it keeps the value 0.

**To Reproduce**
- Set a copy's direction property to any value;
- Change its speed via this.speed;
- Check the new direction value (by logging or etc.).

**Expected behavior**
It is my understanding that this.speed should not interfere with this.direction.

**System information report**
Ct.js v2.0.1 😽 (packaged)

NW.JS v0.59.0
Chromium v96.0.4664.55
Node.js v17.1.0
Pixi.js v5.3.11

WebGL available
WebGL vendor Google Inc. (Intel)
WebGL renderer ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-21.20.16.4627)
OS win32 x64 // Windows_NT 10.0.16299

**Example project (strongly recommended)**
[BugTest.ict.zip](https://github.com/ct-js/ct-js/files/8458104/BugTest.ict.zip)

**Comment by CosmoMyzrailGorynych** [comment]
> Whenever a copy's speed is changed via this.speed, its direction property is reverted to 0 after the speed change. If direction is not changed manually once again, it keeps the value 0.

Nope, it happens only if you change speed from 0 to something else. It doesn't happen if your copy was already moving.
In any case, I've prepared a fix for this issue.

For now, you can use the Nightly version, or change speed first and direction after that.
