### ISSUE TITLE
Desktop builds give a 'Your game won't work like this' message, then works anyway.

### ISSUE THREAD

**Issue by Infinity4872** [ct-js/ct-js-old#339]
**Describe the bug**
The error message you get when trying to run HTML5 locally shows up even on native desktop builds.

**To Reproduce**
1. Export for desktop.
2. Open the build.

**Expected behavior**
The error to not appear.

**System information report**
Ct.js v2.0.2 😽 (packaged)

NW.JS v0.59.0
Chromium v96.0.4664.55
Node.js v17.1.0
Pixi.js v5.3.11

WebGL available
WebGL vendor Google Inc. (Intel)
WebGL renderer ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8935)
OS win32 x64 // Windows_NT 10.0.19044

**Screenshots (recommended)**
![image](https://user-images.githubusercontent.com/89923528/169691005-ea401527-c078-46aa-ad50-5b10d1a985e9.png)

**Example project (strongly recommended)**
None.

**Comment by CosmoMyzrailGorynych** [comment]
This was fixed in the `develop` branch. You can use Nightly releases for now, or await a new public release.
