### ISSUE TITLE
Windows MSI Installer

### ISSUE THREAD

**Issue by Emalton** [ct-js/ct-js-old#349]
It would be great if there was a Windows MSI Installer file included in the releases. It can likely be created with a GitHub action too.

**Comment by CosmoMyzrailGorynych** [comment]
Might use https://wiki.gnome.org/msitools

**Comment by CosmoMyzrailGorynych** [comment]
Also https://www.conjur.org/blog/building-a-windows-installer-from-a-linux-ci-pipeline/

**Comment by Emalton** [comment]
Commenting so this doesn't close!

**Comment by Emalton** [comment]
Commenting so this doesn't close!
