### ISSUE TITLE
fix: bundle libatomic (libatomic.so.1) in linux build

### ISSUE THREAD

**Issue by cat-master21** [ct-js/ct-js-old#350]
**Describe the bug**
When running binary of ctjs from the website if a user does not have libatomic.so.1 shared library then ctjs fails to render.

**To Reproduce**
1. Go to https://github.com/ct-js/ct-js/releases/download/v2.0.2/ct.js.v2.0.2.for.linux64.zip to download linux64 binary build
2. extract zip file.
3. Make sure you do not have *libatomic.so.1* ([Ubuntu](https://packages.ubuntu.com/kinetic/libatomic1), [Fedora](https://packages.fedoraproject.org/pkgs/gcc/libatomic/fedora-rawhide.html#files), etc)
4. run `./linux64/ctjs`

**Expected behavior**
at the first debug output line or somewhere near you will get something like this:

```
[pumkinking@fedora ~]$ /home/pumkinking/Downloads/linux64/ctjs
[20425:20425:0714/111025.636575:FATAL:nw_content_renderer_hooks.cc(53)] Failed to load node library (error: libatomic.so.1: cannot open shared object file: No such file or directory)
```
You will notice that ctjs does not stop and still continues but the window won't appear at all!

**System information report**
(cannot launch ctjs)
```
[pumkinking@fedora ~]$ uname -a
Linux fedora 5.18.10-xm1.0.fc36.x86_64 #1 SMP Sat Jul 9 07:50:42 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Screenshots (recommended)**
![Screenshot from 2022-07-14 11-23-03](https://user-images.githubusercontent.com/96554164/179055060-b214ad85-4490-40f8-bb8a-9f791ff2fbf0.png)

**Comment by leedigital** [comment]
This is not a nwjs or ct.js problem. It is a nodejs dependency, and in that case the simplest solution is to install the dependency, on systems like ubuntu just do **sudo apt-get install libatomic1**.

**Comment by CosmoMyzrailGorynych** [comment]
@leedigital ct.js ideally should not require node.js to be pre-installed.

***

Also, as a side note, Fedora comes with node.js preinstalled, and I never needed to install anything specifically on it to work on ct.js

**Comment by leedigital** [comment]
@CosmoMyzrailGorynych,  

so, the problem is that nw.js is based on nodejs... As this lib is a nodejs dependency, it ends up being a nw.js dependency too. In ubuntu, just do **sudo apt-get install libatomic1** and the problem is solved. It is not a bug of ct.js or nw.js, is a dependency on nodejs.

**Comment by cat-master21** [comment]
Okay so I think this can be closed then. Just make sure to install libatomic library first.
