### ISSUE TITLE
ARM build not launching on M1, Mac OS 13.0.1

### ISSUE THREAD

**Issue by oaklandgit** [ct-js/ct-js-old#397]
**Describe the bug**
Can't run ARM build on M1 Mac, OS 13.0.1

**To Reproduce**
1. Download ARM build for M1 mac:
![CleanShot 2022-11-24 at 08 43 49](https://user-images.githubusercontent.com/421615/203834155-f03b1a73-00d7-46c8-9b1e-5b800e1ffbf9.png)

![CleanShot 2022-11-24 at 08 43 03](https://user-images.githubusercontent.com/421615/203833621-3d0fc4c9-85f4-4434-b711-c04686363db2.png)

2. Find in downloads:

![CleanShot 2022-11-24 at 08 48 13](https://user-images.githubusercontent.com/421615/203834430-9d526a34-83eb-4374-9ebb-ac00bbcb6e66.png)

3. Double click app. "ctjs.app" is damaged and can't be opened…"

![CleanShot 2022-11-24 at 08 50 05](https://user-images.githubusercontent.com/421615/203834679-d7e94acf-0948-4385-b0ca-8e993aa9f00d.png)

5. Ensure this isn't just an issue with an unsigned app by right-clicking instead to open. Same thing:

![CleanShot 2022-11-24 at 08 50 05](https://user-images.githubusercontent.com/421615/203834846-2725d1e5-8737-4229-ab27-ade519110f57.png)

**Expected behavior**
I expected a ".app" file to run, or at least to be prompted to allow it to run.

**System information report**
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Model Number:	MKGT3LL/A
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	8419.41.10
  OS Loader Version:	8419.41.10
```

**Comment by markmehere** [comment]
This makes me 😥

Why Apple has decided to pursue this is a bit of a mystery.

Here is the solution:

https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

**Comment by markmehere** [comment]
There is no other real solution apart from a big cash injection or possibly switching to Electron. We could also link to the above article in our installation information as it seems we are going to be stuck with it.

In fairness, the NW.js M1 builds are by one guy with the NW.js project also complaining it lacks the finances to do proper M1 builds. 😥

**Comment by oaklandgit** [comment]
Thank you @markmehere! That did the trick. I do suggest linking to the article from the downloads page.

**Comment by markmehere** [comment]
Nice! 🎉

**Comment by CosmoMyzrailGorynych** [comment]
> There is no other real solution apart from a big cash injection or possibly switching to Electron.

I mean, we can use Electron…
It will require some work but ct.js had migrated to electron and back previously, and NW.js API usage is pretty minimal — mostly working with clipboard (that can be replaced with vanilla JS) and opening external links and files in OS' default manner. File dialogs are already abstracted in `src/js/additionalShellHandiness.js` and can be tweaked to work both with nw.js and electron.

**Comment by CosmoMyzrailGorynych** [comment]
Added installation instructions to https://comigo.itch.io/ct
Edit: And a warning about ARM to https://ctjs.rocks/download/ as well.
