### ISSUE TITLE
Cat mod gamepad is not working correctly. 

### ISSUE THREAD

**Issue by djds4rce** [ct-js/ct-js-old#401]
**Describe the bug**
On clicking left axis controls it returns callback forever for every frame, even if input was pressed once. Tested on Microsoft Xbox one controller.

`ct.gamepad.getAxis('LStickX')` 
returns a value with very small decimal number after single press for every frame. 

**To Reproduce**
1. Go to catmods and install Gamepad mod.
2.
```
const xAxisStickValue = ct.gamepad.getAxis('LStickX')
console.log(xAxisStickValue);
```
4. Press left axis stick once
5. See value of decimal logged. 

**Expected behavior**

`ct.gamepad.getAxis('LStickX')` 
should return 0 if left axis stick is not pressed. 

**System information report**
Ct.js v3.1.0 😽 (packaged)

NW.JS v0.67.1
Chromium v104.0.5112.80
Node.js v18.7.0
Pixi.js v5.3.11

WebGL available
WebGL vendor Google Inc. (NVIDIA)
WebGL renderer ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)
OS win32 x64 // Windows_NT 10.0.19044

**Screenshots (recommended)**

**Example project (strongly recommended)**
Upload a minimal zipped project that showcases the bug.

**Comment by CosmoMyzrailGorynych** [comment]
You will need to add a condition to your code to mark specific values as a so-called dead zone. The values output from joysticks is what your device tells to ct.js, so your joystick is not perfect and indeed has a small tilt in its resting position.
