### ISSUE TITLE
Broken links and blurry pages

### ISSUE THREAD

**Issue by luckasRanarison** [ct-js/ct-js-old#406]
Here are some really minor issues  I got with the  3.2.0 version. The **"Learning Javascript"** and **"Complete tutorials"** links from the toggle menu don't work, and with the new version the navbar and side bar in the docs pages became blurry (it's not visible on the screenshots though). The menu worked prefectly in the 3.0.1

**To Reproduce**
1. Go to ''the right toggle menu"
2. Click on 'learning javascript or one of the complete tutorial links'
3. ...
4. See 404 error

**Expected behavior**
The docs should be opened

**System information report**
Ct.js v3.2.0 😽 (packaged)

NW.JS v0.67.1
Chromium v104.0.5112.80
Node.js v18.7.0
Pixi.js v5.3.11

WebGL available
WebGL vendor Google Inc. (Google)
WebGL renderer ANGLE (Google, Vulkan 1.2.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
OS linux x64 // Linux 6.0.16-300.fc37.x86_64

**Screenshots**
![Screenshot from 2023-01-09 11-44-03](https://user-images.githubusercontent.com/101930730/211269082-cf43fd38-1f25-4aaa-928c-ccc87e4f3e5a.png)

![Screenshot from 2023-01-09 11-41-52](https://user-images.githubusercontent.com/101930730/211268909-3874ef56-4399-487f-b56d-d1eef5794bba.png)

**Comment by CosmoMyzrailGorynych** [comment]
Was fixed in d4eb5666da3cf9a59ab1e915afa9d0e7c6f937d0
