### ISSUE TITLE
make assets created by web export updateable and cacheable

### ISSUE THREAD

**Issue by godmar** [ct-js/ct-js-old#409]
**Describe the current state of the problem**
Right now, when repeatedly exporting a project for the web and uploading it to a server that doesn't use cache control headers, browsers tend to pick up a cached version based on [heuristic freshness](https://www.mnot.net/blog/2017/03/16/browser-caching#heuristic-freshness) rules.  This means that under default settings it is very difficult for the user to refresh the application, particular on mobile. Even on platforms where a hard refresh is supported, it can cause confusion.

**Describe the solution you'd like**
I think a solution that uses mostly immutable assets should be implemented. This is commonly done in web packaging: assets are served using a URL that has their SHA256 in the file name, as in `/js/main-223af2a423243a22342.js`. If an asset is rebuilt and doesn't change, its name will stay the same.  These assets can then be served with either a cache control header that allows them to be cached indefinitely, but also the default mechanism will "just" work.  At the top-level, only a single file would need to be revalidated, perhaps with a `no-cache` header.   This could be `index.html`, and `ct.js` would be replaced with `ct-<hash here>.js`.
All asserts (`img/` and `snd/`) should be served similarly.

**Describe alternatives you've considered (optional)**
A possible alternative is to have `index.html` immutable and then have `ct.js` be the file that requires a `no-cache` directive.

**Additional context**
I am proposing the use of [Pattern 1 described in this article by Jake Archibald](https://jakearchibald.com/2016/caching-best-practices/) for assets, and of Pattern 2 for a single file (that is, `no-cache` or a small `max-age` even).

**Comment by CosmoMyzrailGorynych** [comment]
WIP
![изображение](https://user-images.githubusercontent.com/3174357/221104835-cecc452e-837a-4e68-bbe1-99392d746600.png)

index.html will be the no-cache file, other assets will use URLs with file hashes in them.

My design is all that executes only when making production builds (export for the web/android/desktop), just running a project inside ct.js won't calculate hashes and will use default names.

---

More (fullyFunctional) WIPs 
![изображение](https://user-images.githubusercontent.com/3174357/221114996-05a81afd-66bd-4a13-b695-0f0fc2172de3.png)

**Comment by CosmoMyzrailGorynych** [comment]
Ok, mostly done.

> :sparkles: Ct.js now adds hash sums of exported files' names to textures, icons, and your game's source code.
> It makes it easier to update your games on your own servers and prevents the usage of outdated assets for your players. Note that index.html file should never be cached — the other assets can now be cached.
> Sounds are currently left with the old behavior as I have bigger plans for them and hashing large sound files is probably not the best idea. If you need to cache-invalidate a sound asset (say, by replacing one sound file with another), you can recreate the sound asset under the same name.

So here is what is now cacheable and updateable:

- [x] All textures
- [x] Icons
- [x] Game's source code
- [x] Game's CSS code
- [ ] Sounds (Will do later with more major updates. Current workaround can be seen above.)
