### ISSUE TITLE
Object undefined in the creation event

### ISSUE THREAD

**Issue by Lozamded** [ct-js/ct-js-old#414]
If I create an object and add it to the room, I try to call the object in his "Creation" event with the "templates.list" I can get a list to the object but If I try the get the copy of the list I get undefined (this does not happen if the object that made the call was created after the room than the called one)

![element2](https://user-images.githubusercontent.com/9289861/232379898-8db02517-a4af-424a-800c-4003e3d013f2.PNG)

In the "Creation" event of "analog_ball":
`console.log(ct.templates.list["element1"]); `
`let element_1 = (ct.templates.list["element1"][0]); `
`console.log(element_1);`

I get in the console when I compile the game:
- I print the list of all objects with a specific name In the room
- The object is on the list
- I try to print the content of the first and only element on that list
- is undefined
![element4](https://user-images.githubusercontent.com/9289861/232380809-a09ec413-db08-4244-9911-53caff6f8ed1.PNG)

I know the possible explanation is that I try to call an object that is not created yet but I can see the object when I list all objects with that name in the room and both objects are static in the room no one is spawned or created by another and usually in my experiences with other engines, the creation frame is called after the creation of all instances in the room

**Comment by CosmoMyzrailGorynych** [comment]
> I know the possible explanation is that I try to call an object that is not created yet but I can see the object when I list all objects with that name in the room and both objects are static in the room no one is spawned or created by another and usually in my experiences with other engines, the creation frame is called after the creation of all instances in the room

That's just how devTools work — they show you the **array**, and it is initially empty, thus direct reference to an element `ct.templates.list["element1"][0]` returns undefined. You see entries in the array itself only because devtools showed you the array after everything else was created.

About execution order and object creation, here is a copycat of a similar question on Discord:

> You can put both references in ct.room. (`ct.room.heroOrIdk = this`)
> When you get a reference to your score widget, you can get a reference to your hero by reading it from a room, and vice versa.
>
> or you can just use `var widget = ct.templates.list['scoreWidget'][0]` directly in your hero, or room. This is usually a more simple and ct.js-esque way to do stuff. Note that _**if you're using this line in OnCreate, depending on copy creation order, the score widget may not yet exist when the character is already created**_. It is perfectly safe to use in Frame events, though, or at any time after the room was started.

The important bit is **_marked_**.
