### ISSUE TITLE
New Language Support: Python

### ISSUE THREAD

**Issue by EdwinRodger** [ct-js/ct-js-old#417]
**Is your feature request related to a problem?**
I am a python programmer and I am new to JavaScript and coffeescript so addition of Python Language will help me as well as many other people create games easily. Also python doesn't have many good packages which help it create good games so integrating python with other projects can be a good alternative.

**Describe the solution you'd like**
Addition of Python besides JavaScript and coffeescript. To create games with python, ctjs can use [brython ](https://github.com/brython-dev/brython) which is basically python (instead of JavaScript) in the browser. Brython can be directly import to html using jsDelivr so no extra installation is required.

**Additional context**
Python is famous language, and many devs learn python as their first language (including me :P) so it will be easier for them to create games. It may also increase reach of ctjs to many other devs who use C/C++ to make their games because python is made upon C and is easy to learn if one has already coded in C/C++.

I know I am asking for a **LOT** but do consider Python as an option.

**Comment by CosmoMyzrailGorynych** [comment]
You should really-really try out CoffeeScript. It was made by Python users
and is almost identical to it in syntax, except it is even simpler.

сб, 10 июн. 2023 г., 19:45 Vaidik Lotan ***@***.***>:

**Comment by EdwinRodger** [comment]
So I checked coffeescript and it is similar to python, thanks for the suggestion!
