### ISSUE TITLE
ct.js v4: replace this.depth with this.zIndex

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#424]
> This is an issue for the upcoming ct.js v4. The development of this version is done in https://github.com/ct-js/ct-js/tree/pixi-v7 branch, until it gets merged into `develop`.

**Describe the bug**
Pixi.js v7 deprecates the `depth` property on DisplayObject and uses `zIndex` instead. Atm the `depth` property is crossed out.

![image](https://github.com/ct-js/ct-js/assets/3174357/8b9e4bcb-6c14-40d8-a29c-4d10f0d3dc28)

`depth` should be replaced in docs, example projects, and ct.js library.

**Comment by btn0s** [comment]
is there more to do here? I'm looking for good initial issues to tackle.

**Comment by CosmoMyzrailGorynych** [comment]
No, it had a merged PR. This was skipped somehow and should be closed.
