### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#45]
In GitLab by @CoMiGo on Feb 24, 2019, 20:45

Though ct.js already auto-saves the project to a recovery file, it would be great to save previous versions in separate files (similar to what YoYo GameMaker does).

Some things to consider:

* it should be configurable, both in the number of backups and in the fact of creating them at all. One will not need backups if they use git or other svn (probably).
* ideally, it should version assets, too. Maybe pack the project to a dated zip file?

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Feb 24, 2019, 21:11

changed the description

**Comment by yonderbread** [comment]
Honestly I don't think it's necessary to incorporate backups into Ct.js, this should be up to the user to set up with an external program. It's best if each program a user has does 1 task instead of many, at least according to the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well).

**Comment by CosmoMyzrailGorynych** [comment]
Ct.js is anything but Unix philosophy. And when you do lose a project, you will need this feature, because you won't have a thought about backing up these important files. Shortly, real-life and real deeds against logic.

The backup function surely needs a toggle, because it will conflict with the stuff you may use when you do set up external backups. (E.g. git, dropbox.)

**Comment by yonderbread** [comment]
Maybe integrating a simple git repo management interface/panel would be beneficial. A lot of users coming to Ct.js are new to programming and it would be awesome if it could introduce them to the world of version control systems.

**Comment by markmehere** [comment]
Not stale. I thought this too. Always disappointing to lose some code while transferring stuff.
