### ISSUE TITLE
Anchored copy positioning

### ISSUE THREAD

**Issue by SysError99** [ct-js/ct-js-old#453]
**Describe the bug**
Whenever the option 'scaling without letterboxing' is chosen, the UI room layer always stick with the top of the screen, ruining overall UI consistency in some cases.

**To Reproduce**
1. Enable `fittoscreen` module.
2. In `Project Settings`, at the `Fit to Screen` options, enable `Scaling without letterboxing` option.
3. Construct the game UI room that respects any aspect ratio.
4. On the game launch, when the viewport gets resized, the UI room only sticks up at the top of the viewport.

**Expected behavior**
There should be configurable options to set the anchor of UI rooms. This way there will be no breaking changes with the current version and gives users more flexible options to design the game. Or the easiest way is to retain every room layer at the center of the viewport (resembles letterboxing option), but it breaks compatibility with previous version.

**System information report**
Ct.js v3.2.0 😽 (packaged)

NW.JS v0.67.1
Chromium v104.0.5112.80
Node.js v18.7.0
Pixi.js v5.3.11

WebGL available
WebGL vendor AMD
WebGL renderer AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.6, DRM 3.49, 6.1.60-1-MANJARO)
OS linux x64 // Linux 6.1.60-1-MANJARO

**Screenshots (recommended)**
UI room configuration:
![Screenshot_20231107_221327](https://github.com/ct-js/ct-js/assets/17522480/eb94cbbb-ff10-4ff6-80ff-c729dc82bb8c)
Runtime with about the same screen aspect ratio as the UI layer:
![Screenshot_20231107_221306](https://github.com/ct-js/ct-js/assets/17522480/1976e0aa-3987-4e81-a11c-49087c30fd83)
Runtime with portrait aspect ratio:
![Screenshot_20231107_221254](https://github.com/ct-js/ct-js/assets/17522480/a6d9fba9-bdf7-4d5b-a7c6-8ea67d7ef778)

**Example project (strongly recommended)**
[2DPhysics.ict.zip](https://github.com/ct-js/ct-js/files/13282547/2DPhysics.ict.zip)

**Comment by CosmoMyzrailGorynych** [comment]
In v3, it is up to a game developer to position their UI elements however they need. It's not a bug. A quick and dirty way you can realign UI in v3 is to [use ct.camera.realign](https://docs.ctjs.rocks/ct.camera.html#ct-camera-realign-room).

**Comment by CosmoMyzrailGorynych** [comment]
Dumping the contents of a draft issue at the Overlook board as this issue is essentially a duplicate:

# Anchored copy positioning

Main use case: positioning of UI elements with a flexible UI layout

Fields:

* Reference frame, two 2D vectors from 0 to 1, for top-left and bottom-right corners.
* paddings, for each side
* Vertical and horizontal alignment
  * ~~can be axis-start (0), axis-middle (0.5), axis-end (1), and fill ('fill')~~
  * ~~when not set to fill, the perpendicular axis' size can be manually changed through regular room editor tools.~~
  * Better make positioning relative to the reference frame as used in Figma/Sketch/Lunacy:

![Image](https://github.com/orgs/ct-js/projects/5/assets/3174357/3cf5a422-7eed-4fb7-80ab-20c38c2c7d0d)


When enabled:

* Copies are put into a special array in the room.
* In room's OnCreate, all the copies in this array are repositioned.
* When used with Scaling with Letterboxing or Expand display modes, repositions copies in that array at every fittoscreen call.

Positioning algorithm:

```js
// get the old reference frame
const {padding, frame} = copy.align;
const xref = oldWidth * frame.x1 / 100 + padding.left,
      yref = oldHeight * frame.y1 / 100 + padding.top;
const wref = oldWidth * (frame.x2 - frame.x1) / 100 - padding.left - padding.right,
      href = oldHeight * (frame.y2 - frame.y1) / 100 - padding.top - padding.bottom;
// get the new reference frame
const xnew = newWidth * frame.x1 / 100 + padding.left,
      ynew = newHeight * frame.y1 / 100 + padding.top;
const wnew = newWidth * (frame.x2 - frame.x1) / 100 - padding.left - padding.right,
      hnew = newHeight * (frame.y2 - frame.y1) / 100 - padding.top - padding.bottom;
if (oldWidth !== newWidth) {
    switch (copy.align.alignX) {
    case 'start':
        break;
    case 'both':
        copy.width += wnew - wref;
        break;
    case 'end':
        copy.x += wnew - wref;
        break;
    case 'center':
        copy.x += (wnew - wref) / 2;
        break;
    case 'scale': {
        const k = wnew / wref || 1;
        copy.width *= k;
        copy.x = (copy.x - xref) * k + xnew;
    } break;
    default:
    }
}

if (oldHeight !== newHeight) {
    switch (copy.align.alignY) {
    case 'start':
        break;
    case 'both':
        copy.height += hnew - href;
        break;
    case 'end':
        copy.y += hnew - href;
        break;
    case 'center':
        copy.y += (hnew - href) / 2;
        break;
    case 'scale': {
        const k = hnew / href || 1;
        copy.height *= k;
        copy.y = (copy.y - yref) * k + ynew;
    } break;
    default:
    }
}
```

**Comment by SysError99** [comment]
Thank you for your dedication to answer the question! I did indeed overlook the manual and I apologise in this regard 😅

Is it possible that this could be an option in the room editor settings? I might be able to take care of this feature but I need to examine the feature first.

**Comment by CosmoMyzrailGorynych** [comment]
Yes, that's the plan for it. Ct.js v4 (in progress) recently got new base classes to choose from, including templates as text labels and as 9-slice planes, and having anchoring tools is an obvious next step. (I added a new Text tool to the room editor, with a plan to make it a UI tweaking tool.)

I will probably start working on it myself after I fix the tiny bugs with editing 9-slice planes and add a simple Container base class.

**Comment by CosmoMyzrailGorynych** [comment]
Done.
