### ISSUE TITLE
Keyboard shortcuts for editor navigation: Close current editor (Esc), and open-by-name (Ctrl+P)

### ISSUE THREAD

**Issue by winterstein** [ct-js/ct-js-old#455]
(Thank you for making this wonderful tool!)

**Is your feature request related to a problem?**
When editing, I often want to switch between scripts, e.g. from a Room Event script to a Template script.
This involves clicking close buttons to navigate up, then clicking items to navigate down. It is a distraction which breaks flow.

**Describe the solution you'd like**
A couple of keyboard shortcuts for editor navigation:

 - Esc: Close the current editor. E.g. from a Room Event script, Esc would be like clicking Done, and would take you to the Room editor. Clicking Esc again would then take you to the Rooms list.
 - Ctrl-P: Open-by-name: This is a really handy feature in e.g. VS Code. Ctrl+P opens a text input, which lets you select a resource to open by name. E.g. if you had Template:Robot, Event:Frame Start, then Ctrl+P then typing a couple of keywords "Robot Start" would let you pick that editor to open.

**Additional context**
Just a big thank you to the ct.js developers :)

**Comment by CosmoMyzrailGorynych** [comment]
Maybe `Ctrl+Enter` for saving? Pressing `Esc` to save is a confusing keyboard to me 🤔 Also ct.js v4 will have a proper save/discard dialog for assets, so maybe Esc will prompt that and Ctrl+Enter will save and close.
