### ISSUE TITLE
Deploying to desktop MAC only (Apple Silicon) gives Exporting the project… Adding desktop resources… Preparing build metadata… Baking icons… Ready to bake packages. Be patient! Building for mac… TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

### ISSUE THREAD

**Issue by pjcoupe** [ct-js/ct-js-old#468]
Did the space shooter tutorial.
Did the deploy to desktop
ticked MAC box only
Hit Export 

Exporting the project…
Adding desktop resources…
Preparing build metadata…
Baking icons…
Ready to bake packages. Be patient!
Building for mac…
Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/private/var/folders/nz/k7lmr51920scqnz8gwdhhww00000gp/T/electron-packager/darwin-x64-template/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'

Apple M1 Max
My macOS is Sonoma 14.1.1

**Comment by pjcoupe** [comment]
Using ct.js Version 3.3.0 (3.3.0)

**Comment by CosmoMyzrailGorynych** [comment]
Will be fixed in ct.js v4. (Switched the framework for packaging for desktop there.)
Current implementation there is not perfect, but definitely simpler and much less error-prone.
