### ISSUE TITLE
"Apply" and "Save" mismatch in buttons inside various asset editors

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#492]
**Describe the current state of the problem**
Some asset editors use a word "Save" to apply changes, but it doesn't write changes to the disk (not their job) and this may lead to confusion.

**Describe the solution you'd like**
All buttons that apply changes of assets must use a word "Apply".

**Additional context**
Tags that use "Save" instead of "Apply":

* room-editor
* texture-editor

**Comment by AnukratiMehta** [comment]
@CosmoMyzrailGorynych 

Hello, I would like to work on this. Please assign it.

**Comment by CosmoMyzrailGorynych** [comment]
@AnukratiMehta Done!
