### ISSUE TITLE
Array custom fields are not being loaded or saved correctly

### ISSUE THREAD

**Issue by minazukitouka** [ct-js/ct-js-old#502]
**Describe the bug**
The editor erroneously saves and loads array fields with a value of -1. This issue arises from the fact that `validateExtends` neglects the array property.

**To Reproduce**
1. Go to 'Assets'
2. Create a behavior
3. Create a custom field of the ref array type (e.g., texture, template)
4. Create a room/template and add that behavior, then click apply to close
5. Reopen the applied room/template, click 'Add a row'
6. See error

**Expected behavior**
It should load and persist with correct values.

**System information report**
Ct.js v4.0.2 😽 (packaged)

**Screenshots (recommended)**
![image](https://github.com/ct-js/ct-js/assets/118855397/5810395d-d252-4ce0-b1fc-de0754f0e1f9)

**Example project (strongly recommended)**
Upload a minimal zipped project that showcases the bug.

**Comment by CosmoMyzrailGorynych** [comment]
Was fixed as part of v5
