### ISSUE TITLE
"Built-in asset gallery" doesn't work

### ISSUE THREAD

**Issue by hojat72elect** [ct-js/ct-js-old#508]
**Describe the bug**
In the main page of the editor, I click on `New Asset / Built-in asset gallery` but instead of seeing a list of available assets, I see an empty dialog with white background. The assets are not loaded.

**Expected behavior**
See a list of available assets.

**System information report**
the x86 version of Apple installer. My device has intel core and am using the osx64 version of the engine.

**Screenshots (recommended)**
<img width="1674" alt="Screenshot 2024-04-05 at 1 56 02 AM" src="https://github.com/ct-js/ct-js/assets/8706521/749b3200-7776-49cc-81b9-526025bd76c2">
<br/>
This is what I see instead of seeing a list of assets.

**Comment by hojat72elect** [comment]
I enabled `DevTools` and this is the error log I get when I click on "Built-in asset gallery" 👇🏼👇🏼

<h3 color="red">index.html:1 Uncaught (in promise) Error: ENOENT: no such file or directory, scandir '/private/var/folders/61/j7t1vs4s0b36jcfppqx_1j8w0000gp/T/AppTranslocation/F0B791DC-66AB-417C-8DBF-D6206141DBE5/d/ctjs.app/Contents/Frameworks/nwjs Framework.framework/Versions/109.0.5414.87/Helpers/nwjs Helper (Renderer).app/Contents/MacOS/bundledAssets/textures'</h3>

Any suggestions how to fix this?

**Comment by CosmoMyzrailGorynych** [comment]
@hojat72elect Do you see any projects on ct.js starting screen in Examples and Templates tabs?

**Comment by hojat72elect** [comment]
@CosmoMyzrailGorynych 

Yes there are some projects shown in those tabs. The problem occurs when I'm in a project and want to add an asset from gallery.


<img width="60%" alt="Screenshot 2024-04-05 at 6 24 57 PM" src="https://github.com/ct-js/ct-js/assets/8706521/721748f0-01c0-417a-a183-c387920b80b1">
<img width="60%" alt="Screenshot 2024-04-05 at 6 25 07 PM" src="https://github.com/ct-js/ct-js/assets/8706521/752f41b4-da13-49e6-8d53-e97181dd45aa">

**Comment by CosmoMyzrailGorynych** [comment]
@hojat72elect I've made a fix at 24326cbc378ec6a9b64d393e65ccdcff7dd9ef83; please download [ct.js Nightly](https://comigo.itch.io/ct-nightly) and see if it indeed fixed the issue. (I don't own a Mac and can't test it myself ¯\\\_(ツ)_/¯ )

**Comment by hojat72elect** [comment]
@CosmoMyzrailGorynych Yes the issue is resolved in nightly build (I tested on OSX x64). Thanks a lot 💖
