### ISSUE TITLE
Floating bug with connected catmod matter.js

### ISSUE THREAD

**Issue by Overloot** [ct-js/ct-js-old#512]
May not occur for a long time. In my case, it happens once a day. Approximately 1 out of 50 project launches in CT

![image](https://github.com/ct-js/ct-js/assets/15037487/f55ee73e-cfab-45d7-9d94-fea3cdccd71c)
![image](https://github.com/ct-js/ct-js/assets/15037487/a55dd8be-8049-43b1-b12f-de10d9820633)

**Comment by CosmoMyzrailGorynych** [comment]
Was fixed some time ago
