### ISSUE TITLE
Pixi's Projection for fast creation of 3D-ish games (ct.3d module)

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#52]
See https://pixijs.io/examples/#/projection/iso-basic.js  
and https://pixijs.io/examples/#/projection/runner.js

The aim is to provide tools for creating games with style similar to Don't Starve, and for making isometric games without having to deal with skewed coordinates.

---

Initial work and examples are made in ct.3d module.
There is some cursed sorcery happening here, so beware. Possible improvements include:

* [ ] Hiding objects that are off-camera — this is really needed. ⚠️
* [ ] Optionally creating 3D sprites from PIXI.Sprite and not from PIXI.AnimatedSprite, so they are transformed properly. ⚠️ Currently, all the copies transform as squares, not as trapezoids. 
* [ ] 3D collisions (boxes and spheres are enough).
* [ ] Everything else :D Like better particle system display, backgrounds, ct.sound.howler 3D sound integration.

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Feb 24, 2019, 21:28

changed the description

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Feb 24, 2019, 21:28

changed the description

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Mar 16, 2019, 16:48

This API will come out as an official feature in pixi.js v5 (see #100)

**Comment by weekendkoder** [comment]
As for 3D. Will there be a chance to mix 3D from lets say three.js ? I mean in a way that my main-character sprite is in 3D and game level is in 2D. But they interact together. So i dont mean a 3D ctJS editor, just a mix of both in the game.

**Comment by CosmoMyzrailGorynych** [comment]
> Will there be a chance to mix 3D from lets say three.js ?

No, this is absurd. Three.js and pixi.js are separate rendering enines tailored for different tasks and they will not work together. You, of course, can stick a 3d model on top of pixi.js canvas, but once you need depth sorting or tighter integration with ct.js, complexity rises exponentially.

In any way, 3D is not part of the scope of ct.js. For 3d, pick another engine.

**Comment by weekendkoder** [comment]
Thx for reply. I have the C2 engine and it has a plugin which you can use threeJS with. Even if its absurd,I find it quite interesting to use it for small tasks. Maybe a plugin could be a chance. Of course, the complexity rises ... here the user can choose. I dont meant to provide a fit threeJS binding inside ctJS, just a possibility. Your engine ctJS looks and feels great to work with it. Thats why i choose it, i was asking for your opinion.

**Comment by CosmoMyzrailGorynych** [comment]
It is not just about complexity from a user's point, but also from a developer's perspective. Such thing will be hard to maintain and distract from more important issues, thus it won't get official. Projection, on the other hand, blends much better with current 2D workflow and will yield great results with fewer efforts, both from end-users and ct.js developers.

The possibility is always here, adding 3D models on top of ct.js is feasible, and it can be an interesting catmod.

**Comment by weekendkoder** [comment]
Sounds understandable. I need to look after "projection", for some 3D-ish effects, i guess. Yeah ... within html you can mix things. But it will require more time & knowledge. So, lets see.

**Comment by CosmoMyzrailGorynych** [comment]
Updated title and added details about the progress and future work.
