### ISSUE TITLE
Invalid font for unsupported languages in the welcome header

### ISSUE THREAD

**Issue by vintprox** [ct-js/ct-js-old#521]
**Describe the bug**

Welcome back jingle phrase on start screen appears in a wrong encoding, one definitely not UTF-8. It's indicative of a locale different from English: and jingles are translated only into Russian.

*Edit:* Welcome header falls back to a wrong font, because the one in ctjs doesn't support a wide range of languages, including Russian.

**To Reproduce**
1. Open ctjs and look at the top.
2. Change language to Russian.
3. Look at the left phrase, it has wrong characters instead of proper cyrillic.

**Expected behavior**

Welcome back jingle phrase should appear in a more fitting font and encoding while in languages different from English.

**System information report**

Ct.js v5.0.0 😽 (packaged)

NW.JS v0.72.0
Chromium v109.0.5414.87
Node.js v19.3.0
Pixi.js v7.3.2

WebGPU UNAVAILABLE
WebGL available
WebGL vendor Google Inc. (AMD)
WebGL renderer ANGLE (AMD, Vulkan 1.3.274 (AMD Radeon Vega 8 Graphics (RADV RAVEN) (0x000015D8)), radv)
OS linux x64 // Linux 6.8.11-300.fc40.x86_64

**Screenshots (recommended)**

Russian:
![ctjs start screen with Russian locale](https://github.com/ct-js/ct-js/assets/5708819/37c04598-b107-49d1-84ec-ad6b8b801326)

English:
![ctjs start screen with English locale](https://github.com/ct-js/ct-js/assets/5708819/10974348-80b1-43db-a2fc-496d5a26e25f)

**Comment by CosmoMyzrailGorynych** [comment]
It's definitely not a problem with the translation file (it's encoding is UTF-8, as it should be), and looks more like a problem with your system's default fonts.

![изображение](https://github.com/ct-js/ct-js/assets/3174357/f336c2ac-fea1-4f50-95b7-9692af2d6f95)

**Comment by CosmoMyzrailGorynych** [comment]
In any way, this welcome header needs a fallback cursive font with a broader language support.

**Comment by vintprox** [comment]
I see, I'll rename the issue to reflect on that.

**Comment by vintprox** [comment]
Few changes in the report description to account for font more than encoding.

Thank you for the quick heads-up, by the way!
