### ISSUE TITLE
Linux: Rendering is broken, results in tiled blinking artifacts

### ISSUE THREAD

**Issue by vintprox** [ct-js/ct-js-old#522]
**Describe the bug**

Game view acts all finicky. Rendering is broken whenever I launch any game in ctjs. It blinks like crazy and is tiling something that looks like an atlas texture artifacts.

Perhaps, this could be a problem with my distribution of Linux? I use Fedora Linux 40. Or could be a thing with Wayland?

**To Reproduce**
1. Open a project.
2. Press "Launch" and wait.
3. See renderer go bonkers.

**Expected behavior**

The game should render normally.

**System information report**

Ct.js v5.0.0 😽 (packaged)

NW.JS v0.72.0
Chromium v109.0.5414.87
Node.js v19.3.0
Pixi.js v7.3.2

WebGPU UNAVAILABLE
WebGL available
WebGL vendor Google Inc. (AMD)
WebGL renderer ANGLE (AMD, Vulkan 1.3.274 (AMD Radeon Vega 8 Graphics (RADV RAVEN) (0x000015D8)), radv)
OS linux x64 // Linux 6.8.11-300.fc40.x86_64

Operating System: Fedora Linux 40
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.8.11-300.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
Memory: 5.7 GiB of RAM
Graphics Processor: AMD Radeon Vega 8 Graphics
Manufacturer: Acer
Product Name: Nitro AN515-43
System Version: V1.09

**Screenshots (recommended)**

<video src="https://github.com/ct-js/ct-js/assets/5708819/1c592559-f8fd-449e-b917-6bb5358bf61a"></video>

**Comment by CosmoMyzrailGorynych** [comment]
Welcome to Vulkan graphics!
You can disable it by going to ct.js main menu — Troubleshooting — Disable Vulkan support. Restart ct.js after that.

**Comment by vintprox** [comment]
Thank you. Disabling Vulkan support and restarting helped.

**Comment by vintprox** [comment]
@CosmoMyzrailGorynych Do players need to tackle the same setting or it's already covered by export settings?

**Comment by CosmoMyzrailGorynych** [comment]
Web exports depend on user's browser (specific Chromium versions are affected), desktop builds use a browser different from what IDE uses. Shouldn't be an issue for web players unless they have an aged Chromium version or forced Vulkan support.
