### ISSUE TITLE
Web Installer fails with "Unknown option 'show-progress'..."

### ISSUE THREAD

**Issue by vintprox** [ct-js/ct-js-old#523]
**Describe the bug**

Using the web installer for Linux proved to be unsuccessful, as it ends with error and no ct.js unpacke anywhere.

```
1) Install or upgrade ct.js
2) Run ct.js
3) Quit
Choose your option: 1
Looking for updates
importing util.sh
importing cursor.sh
importing progress.sh
Using /usr/bin/wget command ...
Looking for updates from https://api.github.com/repos/ct-js/ct-js/releases/latest
Unknown option 'show-progress' /usr/bin/wget -P /home/vintprox/Downloads/.cache --show-progress -q -o /dev/null -c  -O - https://api.github.com/repos/ct-js/ct-js/releases/latest
Press any key to continue ...
```

**To Reproduce**
1. Unpack web installer archive [`ctjs.zip`](https://github.com/leedigital/ct.js-launcher-in-shell-script/releases/download/v1.0.0/ctjs.zip).
2. Set `ctjs.sh` as executable and run in terminal.
3. See the ASCII art of Ct.js and three options.
4. Enter `1` to install.
5. The output is as above.

**Expected behavior**

Expected a sucessful installation, preferrably with no obscure warnings.

**System information report**

Operating System: Fedora Linux 40
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.8.11-300.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
Memory: 5.7 GiB of RAM
Graphics Processor: AMD Radeon Vega 8 Graphics
Manufacturer: Acer
Product Name: Nitro AN515-43
System Version: V1.09

**Screenshots (recommended)**

![Konsole terminal emulator showing ct.js web installer](https://github.com/ct-js/ct-js/assets/5708819/ef18ed4d-e899-4a7e-92b0-66e57fb61f3b)

**Comment by vintprox** [comment]
OK, this seems to be only relevant to release `v1.0.0` installer, as the website had lead me to it instead of v5.

**Edit:** Double nevermind, web installer is another repo altogether and version is right...

**Comment by leedigital** [comment]
The installer requires version 1 of wget, not version 2, wget2.
