### ISSUE TITLE
UI Editor

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#53]
In GitLab by @CoMiGo on Feb 24, 2019, 21:30

Similar to what can be seen in Unreal Engine, this editor should provide visual tools for making HUDs. Actual widgets and complete UI may be represented in a game's code as generated types, with "On Step" events listening to resizing (should be inherited from a class) and updating different values (e.g. health-bars values, text fields, etc.).

This must definitely be written with Pixi.js and can be a simple key-value editor with a tree view of components. Components must be created from a limited palette of pre-maid widgets.

---

### About context (a copy from Discord server)

Ct.js is a bit better at UI in 2D games compared to other engines. But still nothing compared to, say, widget designer in UE4.

The question about implementing UI elements is not about how to implement it, but how to do it right. There are a couple of things to note here:

— We have UI layers now. It is a good progress and hints to code all the UI as separate rooms. Currently, if you stick to textures and use PIXI.Text sparingly, it is actually easy and fun.

— ct.js currently has a poopy room editor that does its minimal job yet doesn't have support for additional fields or live preview. The new room editor will solve these issues. With additional fields, we will be able to set custom pivots to individual copies, solving the problems with aligning. #39 #40

— Ct.js still does not support  type inheritance and choice of base types. But with this and with the new editor, there will be an avenue for WYSIWYG experience and towards reusable UI components.v #77 

— Events. Ct.js has just four, yet with additional and module-provided events it will be easier for users (especially newcomers) to write UI events. This issue also includes the fact that the whole PIXI.Interaction API was overlooked at v1 development.

— Lastly, inputs. Input handling is in a good state, as I see it. It doesn't have anything for hotseat games, yet it is enough currently for UI stuff. Anyways, the way it is written suggests that the inputs part of UI should be a custom code.

So a good and maintainable, evolving solution for ct.js requires sorting out issues with room editing, type inheritance, and the way you program those types.

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Feb 24, 2019, 21:36

changed the description

**Comment by amsam0** [comment]
~~Could I experiment with this and try to make something that works, at least partially?~~

~~I'm going to try and start with `ct.ui` and give base classes there, which are extendable. Should it be a catmod or built in? I have no experience with catmods so I'm starting with built in, but it should be pretty easy to convert.~~ Nevermind.

**Comment by CosmoMyzrailGorynych** [comment]
> Could I experiment with this and try to make something that works, at least partially?

sure

> Also would you mind if I use https://github.com/pixijs/pixi-ui?

I'm afraid it will be too hard to integrate into ct.js, and then even harder into a room editor

**Comment by CosmoMyzrailGorynych** [comment]
Is it? Anyways, I'm doing experiments on that already.

**Comment by CosmoMyzrailGorynych** [comment]
No
