### ISSUE TITLE
What the HECK is the "Split Death" bug and how to get rid of it?!

### ISSUE THREAD

**Issue by ChocolateBarCatGames** [ct-js/ct-js-old#533]
![image](https://github.com/user-attachments/assets/3e7810e3-baaa-40aa-887a-21a8eb73975e)
The Split Death bug is when you are trying to export your project and it says "cannot define script". Sometimes it even keeps your from running the project.
But how do I get rid of it?!

To get this bug all you have to do is MIND YOUR OWN BUISNESS ON A PROJECT UNITL IT TELLS YOU THAT.
I expected it to just run my project.

I love ct.js but this is disappointing... does anyone have any clues on how to get this bug away?!

**Comment by CosmoMyzrailGorynych** [comment]
Please use the issue template and specify reproduction steps, system information, example project, etc.
I can't do anything with the information you've provided.

**Comment by ChocolateBarCatGames** [comment]
> Please use the issue template and specify reproduction steps, system information, example project, etc. I can't do anything with the information you've provided.

Yeah, its not your fault
i couldnt really think that anyone wouldve really figured it out... not your fault. :3
