### ISSUE TITLE
Visual overflow in confirmation dialog

### ISSUE THREAD

**Issue by benjammin4dayz** [ct-js/ct-js-old#537]
**Describe the bug**

In cases when many loose assets (or a few assets with really long names) are deleted at once, the confirmation dialog can overflow beyond the viewport. This behavior obscures the dialog choices and leaves the user with no evident option to proceed.

**To Reproduce**

1. Create a new project in the ct.js app (v5.1.0)
2. Visit the Assets page
3. Click the "New Asset" button
4. Select "Built-in asset gallery"
5. Find and select "Kenney's Platformer" in the asset gallery
6. Click the "Import all" button
7. Return to the Assets page
8. Shift-click the **first** item in the Assets list
9. Scroll down and shift-click the **last** item in the Assets list
10. Right-click any highlighted asset and select "Delete"

**Expected behavior**

The list is displayed within a scrolling container with limited height and could potentially be truncated beyond N items.

**System information report**

Win11 x64

**Screenshots (recommended)**

https://github.com/user-attachments/assets/6182265f-112d-4d89-8495-7b8025dbf94d

**Comment by CosmoMyzrailGorynych** [comment]
Putting two changes here: most dialog boxes will now be limited by height, plus this particular dialog will have at max 10 items listed for the sake of being readable by humans:

![изображение](https://github.com/user-attachments/assets/52db9f96-ff6f-4680-a014-ad8ead346a2c)
