### ISSUE TITLE
Cannot put img or use built-in asset gallery with the project contain "#" in the name

### ISSUE THREAD

**Issue by Cartoons12** [ct-js/ct-js-old#543]
**There might be other naming issues, u should check it out**

  **Describe the bug**
Naming a project including this special character will broke ctjs: "#"
You can do it but cannot import  img file into it nor using built-in asset gallery.

  
  **To Reproduce**
  1. Create a new project in ctjs that have the "#" character in its name
  2. See error
  
  **Expected behavior**
Work normally 
  
  **Screenshots (recommended)**
![image](https://github.com/user-attachments/assets/2d69a920-9a8b-4c64-8b0d-3fd346fa555e)

  
  **Example project (strongly recommended)**
[#Bug.zip](https://github.com/user-attachments/files/16921213/Bug.zip)

**Comment by CosmoMyzrailGorynych** [comment]
Project creation form states that the project name must contain letters and digits only — project names with `#` are not supported. The bug is that the project creation form does not check the given value for special characters.
