### ISSUE TITLE
what irritates

### ISSUE THREAD

**Issue by returnworld** [ct-js/ct-js-old#545]
1)Moving the view scope when editing a room with the mouse wheel is very uncomfortable, could you change it to the right mouse button (if you are not going to add a popup context menu) or at least to the spacebar.

2)During room editing, when we select a copy (template) to add, it is impossible to cancel, by right click or escape, we have to reach every time for an empty None template.

please fix this, i think many people will like it (^_^)

**Comment by CosmoMyzrailGorynych** [comment]
> 1)Moving the view scope when editing a room with the mouse wheel is very uncomfortable, could you change it to the right mouse button (if you are not going to add a popup context menu) or at least to the spacebar.

There are context menus for the Select tool already, so no right-clicks to navigate.
Rn you can use Alt+Shift and left mouse button to navigate around. Spacebar alternative would indeed be a good addition.

> 2)During room editing, when we select a copy (template) to add, it is impossible to cancel, by right click or escape, we have to reach every time for an empty None template.

Having "None" selected has no functional purpose, why would you ever leave that on? You can use QWERTY hotkeys btw to switch between tools on the right side of the room editor.
