### ISSUE TITLE
When I'm trying to use in template event, variable created in some room event that has clone of that template I cannot use it.

### ISSUE THREAD

**Issue by 111ukasz111** [ct-js/ct-js-old#550]
**Describe the bug**
When I'm trying to use in template event, variable created in some room event that has clone of that template I cannot use it.

**To Reproduce**
1. Go to room editor
2. Click on Events
3. Add room start event to edited room
4. Write " this.test = 100;" in room start event.
5. Go to some template that is in this room.
6. Add creation event and write "this.direction = rooms.current.test;" in creation event
7. When I run game this template "Ball" is destroyed.

**Expected behavior**
Variable "test" should be usable from template event of template that is in this room.

**System information report**
Ct.js v5.2.1 😽 (packaged)

NW.JS v0.72.0
Chromium v109.0.5414.87
Node.js v19.3.0
Pixi.js v7.3.2

WebGL available
WebGL vendor Google Inc. (NVIDIA)
WebGL renderer ANGLE (NVIDIA, NVIDIA GeForce 920M Direct3D11 vs_5_0 ps_5_0, D3D11)
OS win32 x64 // Windows_NT 10.0.19045

**Screenshots (recommended)**
![Zrzut ekranu (2)](https://github.com/user-attachments/assets/f6c62fd1-734c-4995-b2b4-c4791a6eb8b6)
![Zrzut ekranu (3)](https://github.com/user-attachments/assets/4db4d39d-6d8f-46ac-a67f-b9f99b548b95)

**Example project (strongly recommended)**
[PongInJs.ict.zip](https://github.com/user-attachments/files/17623292/PongInJs.ict.zip)

**Comment by CosmoMyzrailGorynych** [comment]
Works as intended.
Room Start events are run after all the templates are created, so you can reference the created templates and tilemaps. Use global variables or extensions (the last argument of rooms.append/rooms.prepend and "Additional options" in Catnip) to predefine shared variables, and do it before the room switch.

**Comment by 111ukasz111** [comment]
How to do it in javascript?

> Works as intended. Room Start events are run after all the templates are created, so you can reference the created templates and tilemaps. Use global variables or extensions (the last argument of rooms.append/rooms.prepend and "Additional options" in Catnip) to predefine shared variables, and do it before the room switch.

How to do it in javascript?

**Comment by 111ukasz111** [comment]
But Im trying to do this "this.test = rooms.current.test;". While I have created "this.test = 100;"variable in editors event.
How to make shared variables in javascript?

**Comment by CosmoMyzrailGorynych** [comment]
If you use room's "Room start" event to define your properties, they are defined **_after_** your templates are created, thus a template cannot read that property from their own "Creation" event.

**Comment by CosmoMyzrailGorynych** [comment]
You can define "global"-like variables in a custom script (Project tab -> Custom Scripts). A simple `var test = 100;` will be enough. Then, in a template, use `this.speed = test;`. To change that value later, use regular `test = 150;` where you need it.
Custom scripts are run before the game starts and are executed at the very top of the game's code, so they will be available everywhere everytime.

**Comment by 111ukasz111** [comment]
> You can define "global"-like variables in a custom script (Project tab -> Custom Scripts). A simple `var test = 100;` will be enough. Then, in a template, use `this.speed = test;`. To change that value later, use regular `test = 150;` where you need it. Custom scripts are run before the game starts and are executed at the very top of the game's code, so they will be available everywhere everytime.

thx and sorry for my stupidity.
