### ISSUE TITLE
running multiple copies of an executable

### ISSUE THREAD

**Issue by returnworld** [ct-js/ct-js-old#559]
It would be great to add the ability to run multiple copies of ct.js on windows, it will help a lot in the learning and development process, when you want to look, remember how something is done in examples or in your old projects. Now I constantly have to switch between projects to remember what events I used and to copy a few lines of code.

I think this is done by changing just one flag when building *.exe

**Comment by CosmoMyzrailGorynych** [comment]
After opening a project, go to the main menu -> Open new project window (or something like that. It is in the first block of options.)

As far as I recall, latter versions of nw.js do not support running multiple instances of an app, thus new windows had be opened from inside ct.js. It will probably also be changed when ct.js finally migrates to Neutralino + Bun.
