### ISSUE TITLE
Graphics management overhaul

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#60]
In GitLab by @CoMiGo on Feb 27, 2019, 20:08

So the current graphics editor simply shows you a sprite sheet and allows you to set how this sprite sheet will be later divided in the game. This fact brings a bunch of issues:

* it is expected that a user has a sprite sheet. Individual frames need to be joined before importing (bad workflow, excessive tasks);
* ~~Pixi.js leaks pixels on scaled copies when is run on WebGL. Padding on edges is needed;~~ (solved in https://github.com/ct-js/ct-js/commit/ba52f95073c8e52d01373d62f4d97c256ddb71ed)
* no edit tools for frames, no reordering, cropping, scaling, etc.

The plan is to split graphics editor into sections:

* Image splicer (a temporary one that will disappear when the image is split);
* Collision shape editor;
* Animation/frame editor.

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Feb 27, 2019, 20:16

changed the description

**Comment by CosmoMyzrailGorynych** [comment]
I thought about it more and now think that the textures editor doesn't really require heavy editing, but rather adding a layer of additional features. Everything may be kept in one view. E.g. click on a frame → a new toolbar slides in → you can now rotate, flip, recolor this frame. More general tools like resizing and adding new frames may be displayed at the bottom.

*Or* the texture editor may display multiple individual frames at once but work on one source image. An image slicer can be introduced as a separate button in the texture panel, next to "Import".

Issues with Pixi are solvable by modifying exporter.js and are not tied to texture editor in any way. The exporter may draw each frame in its individual location in the atlas, and ct.js already supports such layout.

**Comment by CosmoMyzrailGorynych** [comment]
I hate mockups, but here is [a rough depiction](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&nav=1&title=Texture%20management_vision01.drawio#Uhttps%3A%2F%2Fraw.githubusercontent.com%2FCosmoMyzrailGorynych%2Fct-js-mockups%2Fmaster%2FTexture%2520management_vision01.drawio) of what may be a new texture manager.

**Comment by CosmoMyzrailGorynych** [comment]
> Pixi.js leaks pixels on scaled copies when is run on WebGL. Padding on edges is needed;

Solved in https://github.com/ct-js/ct-js/commit/ba52f95073c8e52d01373d62f4d97c256ddb71ed

**Comment by weekendkoder** [comment]
Will there be a possibility to add SVG / div Dom / vector to the room-scene so ctJS can convert it on-the-fly to a bitmap ? This way, i guess, you can make very small builds !

**Comment by CosmoMyzrailGorynych** [comment]
This issue is about managing raster sprites. SVGs are rare cases and are not on our roadmap.

**Comment by weekendkoder** [comment]
Ok, i now that pixiJS has some loader-function for SVG. I was curios if it works with ctJS ...

**Comment by CosmoMyzrailGorynych** [comment]
Technically, this stuff is achievable, yet SVG sprites are out of scope.
You should better create a separate issue with a feature request for SVG support.

**Comment by weekendkoder** [comment]
I will do a request, soon.
