### ISSUE TITLE
Particle system editor and module

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#62]
The editor is surely in ct.ide's scope, but it still requires something to edit :)

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Mar 2, 2019, 17:23

http://pixijs.download/release/docs/PIXI.particles.ParticleContainer.html

**Comment by Tyrannas** [comment]
https://github.com/pixijs/pixi-particles Could this be an option to integrate a particle system instead of the PIXI basic one? 
And if I wanted to use it from scratch what could I do, copy/paste the code in a new Settings > Script ?

**Comment by CosmoMyzrailGorynych** [comment]
> Could this be an option to integrate a particle system instead of the PIXI basic one?

Yes, it could be, and will probably be used.

>  And if I wanted to use it from scratch what could I do, copy/paste the code in a new Settings > Script?

The first step is installing an npm package of it and extracting a minified script from its `dist` folder. 
[Here it is](https://github.com/ct-js/ct-js/files/3748632/pixi-particles.min.txt) so you don't need to dig inside the package.

Copy and paste its contents to a new script in the settings tab.

Then let's say that I need to add an emitter to a Robot character. I'll take an example code from the [Sample Usage section](https://github.com/pixijs/pixi-particles#sample-usage) of `pixi-particles`. I will need to modify it so it can find ct.js' textures and append the emitter to a copy:

![](https://user-images.githubusercontent.com/3174357/67170009-238c7e80-f403-11e9-91c0-3f38b9c49155.png)

Then, put this line to the OnStep event:

`this.emitter.update(ct.delta/60);`

I also modified the colors from that example, and that's what I got:
![](https://user-images.githubusercontent.com/3174357/67170064-6c443780-f403-11e9-9e8c-74267e468f34.png)

**Comment by Tyrannas** [comment]
Wow thank you for the very complete answer! That's great!
If I may just ask a naive question, why is the Emitter updated in the onStep section and not in the onDraw ?

**Comment by Tyrannas** [comment]
By the way, I found a potential source of bug when the integration of the particle system will be done.
When creating an emitter there is an option allowing to set the emitter *behind* the sprite. 
This does not work with ct.tex though, the emitter will always be on top. 
A current workaround is to do this: 
```javascript
this.tex = -1
this.sprite = this.addChild(new PIXI.Sprite(ct.res.getTexture('my_texture')))
```
which will do the trick

**Comment by CosmoMyzrailGorynych** [comment]
> why is the Emitter updated in the onStep section and not in the onDraw?

Because I didn't think about it much at that time (: It is indeed better to be put in the On Draw event.

**Comment by CosmoMyzrailGorynych** [comment]
Closed in https://github.com/ct-js/ct-js/commit/fd3ee760d14add3161f76b5b492b64887d6ec329 :tada:
