### ISSUE TITLE
Gamepad Support

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#63]
See

* https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API
* https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API
* [docs on building new catmods](https://docs.ctjs.rocks/making-mods.html#structure-of-module-json) and specifically [how to add new input methods](https://docs.ctjs.rocks/making-mods.html#adding-new-input-methods)
* [ct.keyboard](https://github.com/ct-js/ct-js/tree/develop/app/data/ct.libs/keyboard) source

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Feb 28, 2019, 01:50

changed the description

**Comment by leedigital** [comment]
This one I would like to help. After I finish translating the [official documentation](https://docs.ctjs.rocks/) into Brazilian Portuguese. ^_^

**Comment by CosmoMyzrailGorynych** [comment]
@leedigital Then you better help @Atavismus with that as they already started making this module ;) They are `SN` at our Discord server

**Comment by leedigital** [comment]
> @leedigital Then you better help @Atavismus with that as they already started making this module ;) They are `SN` at our Discord server

OK. My name on the Discord server is araujo921, I'll send him a message. ^_^

**Comment by CosmoMyzrailGorynych** [comment]
Closed in https://github.com/ct-js/ct-js/commit/2210fde63db5946336976118a54f5c1b15be0250
