### ISSUE TITLE
Scriptable trigger zones in room editor

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#67]
Related: #39

**Comment by ghost** [comment]
I would love to help make trigger zones, but I don't exactly understand what you mean by a "trigger zone", would it be an invisible-to-the-player object that can be dragged into the room and when in view or in a specific range from the view would trigger a function set by the user? or would it be an invisible-to-the-player object that triggers a function when a specified object touches it?

**Comment by CosmoMyzrailGorynych** [comment]
Yes.
